frappe/press

press/press/doctype/site/site.py
ref: https://github.com/frappe/agent/pull/36/commits/b549efa9bfac33bf3705db95f2c3b37b66383694
=> feat: Show different suspension template on proxy for SaaS

press/press/doctype/marketplace_app/templates/marketplace_app.html, press/templates/marketplace/base.html
Before: 
[Image Coming]
After:
[Image Coming]
=> feat(marketplace): Show app title in web page title

dashboard/src/views/SiteDatabaseBackups.vue, dashboard/src/views/SiteOverview.vue, dashboard/src/views/saas/SubscriptionSettings.vue, press/api/saas.py, press/saas/doctype/saas_settings/saas_settings.json
<strong>Setup</strong>
* Add app to bench and deploy new bench.
* Add the app to whitelisted apps child table in Saas Settings doctype
* Once this is it should show on Saas dashboard in Settings section for Apps
* Currently there's no ui to see the jobs or job progress. The site site status should the give the indication if the app is installing or not.
=> feat(saas): Provision for installing whitelisted apps

press/press/doctype/backup_restoration_test/backup_test.py
=> fix: check empty list

press/api/saas.py, press/press/doctype/site/saas_pool.py, press/press/doctype/site/saas_site.py, press/press/doctype/site/site.json, press/saas/doctype/account_request_rules/account_request_rules.json, press/saas/doctype/account_request_rules/account_request_rules.py, press/saas/doctype/hybrid_saas_pool/hybrid_saas_pool.js, press/saas/doctype/hybrid_saas_pool/hybrid_saas_pool.json, press/saas/doctype/hybrid_saas_pool/hybrid_saas_pool.py, press/saas/doctype/hybrid_saas_pool/test_hybrid_saas_pool.py, press/saas/doctype/saas_pool_rules/saas_pool_rules.json, press/saas/doctype/saas_pool_rules/saas_pool_rules.py, press/saas/doctype/saas_settings/saas_settings.json
* SaaS Pool that contains sites that have a hybrid configuration(i.e. different apps installed, different site configs, etc)
* ERPNext SMB has a requirement to install [India Compliance App](https://github.com/resilient-tech/india-compliance) for `Indian customers only`
* Since SMB runs on SaaS flow the current pool model restricts any dynamic functionality. In the current pooling logic all the sites that are created have same configuration (i.e. apps, configs, plans, etc) which is read from `Saas Settings` doctype.
* If we were to install India Compliance for Indian customers only we need sites in the pool that have different apps installed or different configuration altogether
* Install the app if the Account Request with country "India" is recorded; Sure this works but the app might …
=> feat(saas): Hybrid SaaS Pools

press/press/doctype/marketplace_app/templates/marketplace_app.html
=> fix(marketplace): documentation link label

.gitignore, package.json, press/public/js/marketplace.bundle.js, press/templates/marketplace/base.html, press/www/marketplace/index.html, yarn.lock
Uses [fusejs.io](https://fusejs.io) for the 🤯 fuzzy searching.
Will write more here soon.
=> feat: App Search in Marketplace website

dashboard/src/components/AppPlanCard.vue, dashboard/src/components/global/Badge.vue, dashboard/src/views/MarketplaceAppPricing.vue, press/api/marketplace.py, press/press/doctype/marketplace_app/marketplace_app.py
1. Show if the plan is enabled or disabled
2. Let the user disable / enable via checkbox in edit form
=> feat: Enable / Disabled App Plans from UI

press/press/doctype/site_migration/site_migration.js, press/press/doctype/site_migration/site_migration.json, press/press/doctype/site_migration/site_migration.py, press/press/doctype/version_upgrade/version_upgrade.js, press/press/doctype/version_upgrade/version_upgrade.py
- feat(SiteMigration): Add option to skip failing patches
- fix(SiteMigration): Don't start migration on insert
- fix(VersionUpgrade): Don't start version upgrade on insert
=> fix(SiteMigration): minor UX

press/press/doctype/erpnext_site_settings/erpnext_site_settings.py
=> fix: handle config with no limits

press/press/doctype/marketplace_app/marketplace_app.json, press/press/doctype/release_group/release_group.json, press/press/doctype/site/site.json, press/press/doctype/subscription/test_subscription.py
Refactor the forms to use the new tab breaks feature.
Also Fixes #516
=> refactor: Clean up primary master forms tab using breaks

press/press/doctype/app_release/app_release.py, press/press/doctype/app_release_difference/app_release_difference.json, press/press/doctype/app_release_difference/app_release_difference.py, press/press/doctype/deploy_candidate_difference/deploy_candidate_difference.py
- autoname is slow and not needed in app_release
- deploy_type need not be set while creation of difference
=> fix: defer release diff until deploy

dashboard/src/components/BackupFilesUploader.vue, dashboard/src/views/site/NewSiteRestore.vue, press/press/doctype/site/site.py
Allow desk users to update site_config from the site doc itself.
=> feat: update site_config from desk

nginx.conf
https://github.com/frappe/press/issues/591
=> fix: increase upload size (50M -> 250M)

nginx.conf
Reverts frappe/press#598
Wrong nginx.conf updated. Have to update the template on agent.
=> Revert "fix: increase upload size (50M -> 250M)"

press/press/doctype/version_upgrade/version_upgrade.py
fixes https://github.com/frappe/press/issues/559
=> fix: validate version upgrade before insert

press/docker/Dockerfile-Bench-Update, press/press/doctype/deploy_candidate/deploy_candidate.py
Fixes https://github.com/frappe/press/issues/568
=> feat: Update bench in dockerfile

press/press/report/server_stats/server_stats.py
* added precision
* added server column
* corrected data args
=> fix: server stats report

press/agent.py, press/press/doctype/site/site.js, press/press/doctype/site/site.py
=> feat(Site): Add button to retry archive

dashboard/src/App.vue, dashboard/src/components/Navbar.vue, dashboard/src/components/marketplace/MarketplaceAppReviewStages.vue, dashboard/src/views/marketplace/MarketplaceAppReview.vue, dashboard/src/views/marketplace/MarketplaceApps.vue, dashboard/src/views/site/SiteOverviewAppsAndSubscriptions.vue, press/api/marketplace.py
Developer-Publisher communication
=> feat: Marketplace review improvements and misc fixes

dashboard/src/App.vue, dashboard/src/components/Sidebar.vue, dashboard/src/router/auth.js, dashboard/src/views/checkout/Checkout.vue, dashboard/src/views/checkout/CheckoutAddress.vue, dashboard/src/views/checkout/CheckoutApps.vue, dashboard/src/views/checkout/CheckoutConfirmEmail.vue, dashboard/src/views/checkout/CheckoutPayment.vue, dashboard/src/views/checkout/CheckoutPlans.vue, dashboard/src/views/checkout/CheckoutStripe.vue, dashboard/src/views/marketplace/MarketplaceApp.vue, dashboard/src/views/server/ServerList.vue, press/api/developer/marketplace.py, press/api/marketplace.py, press/press/doctype/payout_order/payout_order.py
Components now will be,
* more aligned with dashboard styles
* more responsive
* easier to manage
Keep previous flow for now because, backward compatibility.
=> refactor: Move saas(iframe) checkout screens to dashboard components

dashboard/src/components/Sidebar.vue, dashboard/src/controllers/account.js, dashboard/src/views/auth/SetupAccount.vue, dashboard/src/views/settings/AccountTeam.vue, dashboard/src/views/site/Site.vue, press/api/account.py, press/api/bench.py, press/api/server.py, press/api/site.py, press/marketplace/doctype/marketplace_app_subscription/marketplace_app_subscription.py, press/press/doctype/account_request/account_request.json, press/press/doctype/child_team_member/child_team_member.json, press/press/doctype/child_team_member/child_team_member.py, press/press/doctype/site/site.py, press/press/doctype/subscription/subscription.py, press/press/doctype/team/team.json, press/press/doctype/team/team.py, press/press/doctype/usage_record/usage_record.py, press/saas/doctype/saas_app_subscription/saas_app_subscription.py
* Now a team can be considered as a child team to avoid creating two separate invoices
* Usage Records for the child team are made under the parent team account
* Common Invoice is created for both the parent and child teams.
* Create/Invite a child team from the dashboard
* Switch to child team
* Transfer a site to another team from dashboard
* Hide Billing section from child team 
* Parent team can see all the sites and benches from its child teams.
=> feat: create common invoice for child and parent team

dashboard/src/views/billing/AccountBillingPayments.vue
=> feat: add payment date to dashboard

press/press/doctype/bench/test_bench.py, press/press/doctype/site/test_site.py, press/press/doctype/site_domain/test_site_domain.py
Only fixed some. Will push directly as I go.
=> Fixup tests

press/press/report/binary_log_browser/binary_log_browser.py, press/press/report/mariadb_slow_queries/mariadb_slow_queries.py
ref: https://github.com/frappe/frappe/pull/20253
=> fix: use get_system_timezone instead of get_time_zone

press/hooks.py, press/press/doctype/razorpay_payment_record/razorpay_payment_record.py, press/utils/billing.py
fetch pending razorpay orders every 6 hours
=> feat: fetch pending razorpay payments

press/api/github.py
Closes https://github.com/frappe/press/issues/775
=> fix: Allow Apps with any one setup file

dashboard/index.html, dashboard/package.json, dashboard/src/main.js, dashboard/yarn.lock, press/api/account.py, press/api/developer/marketplace.py, press/api/site.py, press/auth.py, press/press/doctype/account_request/account_request.py, press/press/doctype/team/team.py, press/templates/emails/verify_account.html, press/utils/telemetry.py, press/www/dashboard.py
Client side setup
&
Tracking
1. FC Signup
- Verification email sent
- Email read
- Added card or paid for prepaid credits
- Created site
=> feat(telemetry): Frappe Cloud signups and onboarding

press/api/saas.py, press/press/doctype/marketplace_app/marketplace_app.json, press/press/doctype/site/saas_pool.py, press/press/doctype/site/saas_site.py, press/press/doctype/site/site.py, press/press/doctype/storage_integration_subscription/storage_integration_subscription.py, press/saas/doctype/saas_settings/saas_settings.json, press/utils/__init__.py
Fixes https://github.com/frappe/press/issues/841
=> refactor: Run the update site config steps while creating the site

dashboard/src/views/bench/BenchApps.vue
fix #496
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> feat: show update app alert in `Apps` tab

dashboard/src/views/bench/BenchApps.vue, press/api/bench.py
fix #594 
https://github.com/frappe/press/assets/63963181/9cbc2bbd-b78b-44f6-9a9c-a1dac06ca392
=> feat: multiple app selection for `BenchApps`

dashboard/src/utils.js
=> refactor(formatDuration): `HH:MM:SS` ->  `HHh MMm SSs`

dashboard/src/views/bench/Bench.vue, press/api/bench.py
=> feat: option to update all sites to latest version

dashboard/src/views/site/SiteDatabaseBackups.vue, press/api/site.py, press/press/doctype/site_backup/site_backup.json, press/press/doctype/site_backup/site_backup.py
fix #606 
depends on frappe/agent#56
=> feat: add `site_config_file` download option

dashboard/src/views/billing/AccountBillingPayments.vue, dashboard/src/views/site/Sites.vue, press/api/billing.py, press/press/doctype/team/team.py
fix #805 
https://github.com/frappe/press/assets/63963181/c60b245b-0825-4b95-b3e8-8b1aea455cd5
=> fix: route to /billing while clicking on alert for unpaid invoices

dashboard/src/views/site/SiteOverviewAppsAndSubscriptions.vue
=> style(site-apps): show commit tag beside app name always

dashboard/src/views/bench/BenchDeploys.vue
=> feat: add time stamps for running and failed deploys

dashboard/src/views/bench/BenchDeploys.vue, press/press/doctype/deploy_candidate/deploy_candidate.py
=> fix: running realtime jobs being updated in other jobs

dashboard/src/components/MarketplaceAppReleaseList.vue, dashboard/src/resourceManager/ResourceManager.js, dashboard/src/views/bench/BenchDeploys.vue, dashboard/src/views/bench/BenchJobs.vue, dashboard/src/views/server/ServerJobs.vue, dashboard/src/views/server/ServerPlays.vue, dashboard/src/views/site/SiteActivity.vue, dashboard/src/views/site/SiteJobs.vue, dashboard/src/views/site/SiteRequestLogs.vue
When there are no more items to load the load more button used to hang around
https://github.com/frappe/press/assets/63963181/d584e73c-9bab-4b61-b961-ec888b7f37c1
https://github.com/frappe/press/assets/63963181/acfd11bc-9fc4-4af4-8524-c90cd0a01d59
=> fix: better paging logic

dashboard/src/views/server/NewSelfHostedServer.vue, dashboard/src/views/server/SelfHostedServerVerify.vue, press/api/selfhosted.py, press/press/doctype/self_hosted_server/self_hosted_server.js, press/press/doctype/self_hosted_server/self_hosted_server.json, press/press/doctype/self_hosted_server/self_hosted_server.py, press/press/doctype/site/site.js, press/press/doctype/site/site.py, press/press/doctype/subscription/subscription.py
- Earlier logic didn't take in Plan Change doctype, added that
- Update verify page to add SSH key to `authorised_keys`. This was a dumb bug which I had initially put for development which I later forgot 🙈 
- Added a button for enabling/disabling read_write mode for DB
- Fetch RAM from Ansible ping results for better auto-scaler allocation
=> Subscription Creation for BYOD servers

.github/workflows/main.yaml, press/marketplace/doctype/marketplace_app_subscription/marketplace_app_subscription.json, press/marketplace/doctype/marketplace_app_subscription/marketplace_app_subscription.py, press/marketplace/doctype/marketplace_app_subscription/test_marketplace_app_subscription.py, press/press/doctype/invoice/invoice.py, press/press/doctype/site/test_site.py, press/press/doctype/subscription/subscription.py, press/press/doctype/team/team.py, press/press/doctype/usage_record/usage_record.py
=> refactor: Merge MarketplaceAppSubscription with Subscription for creating usage records

dashboard/src/views/billing/AccountBillingPayments.vue, press/api/billing.py, press/press/doctype/team/team.py
Use "Pay Now" button to refresh expired link.
fixes https://github.com/frappe/press/issues/828
=> feat: allow users to refresh stripe payment url

dashboard/src/views/marketplace/MarketplaceAppAnalytics.vue, press/api/analytics.py, press/press/doctype/marketplace_app/marketplace_app.py, press/press/doctype/press_settings/press_settings.json
=> feat: Marketplace developer analytics

dashboard/src/components/Tags.vue, dashboard/src/router/bench.js, dashboard/src/router/server.js, dashboard/src/router/site.js, dashboard/src/views/bench/Bench.vue, dashboard/src/views/bench/BenchSettings.vue, dashboard/src/views/bench/Benches.vue, dashboard/src/views/server/Server.vue, dashboard/src/views/server/ServerSettings.vue, dashboard/src/views/server/Servers.vue, dashboard/src/views/site/Site.vue, dashboard/src/views/site/SiteSettings.vue, dashboard/src/views/site/Sites.vue, press/api/bench.py, press/api/dashboard.py, press/api/server.py, press/api/site.py, press/press/doctype/database_server/database_server.json, press/press/doctype/press_tag/press_tag.js, press/press/doctype/press_tag/press_tag.json, press/press/doctype/press_tag/press_tag.py, press/press/doctype/press_tag/test_press_tag.py, press/press/doctype/release_group/release_group.json, press/press/doctype/resource_tag/resource_tag.json, press/press/doctype/resource_tag/resource_tag.py, press/press/doctype/server/server.json, press/press/doctype/site/site.json
https://github.com/frappe/press/issues/707
https://github.com/frappe/press/issues/597
=> feat: Add, remove, create tags and filter list views using them

press/press/doctype/site/saas_site.py
* pick benches from random clusters
* pick benches with servers that have least number of sites
=> fix: Better saas bench selection logic

press/press/doctype/site_backup/test_site_backup.py
=> test: site backup

dashboard/src/components/AlertUpdate.vue
Closes https://github.com/frappe/press/issues/928
=> chore: Change description of deploy bench

dashboard/vite.config.js
closes https://github.com/frappe/press/issues/839
=> fix: enable sourcemaps

dashboard/src/views/site/SiteAnalyticsUptime.vue
=> refactor(uptime-graph): better hover message

press/patches.txt, press/press/doctype/release_group/patches/sync_common_site_config.py
=> chore: add patch for syncing common_site_config

dashboard/src/views/bench/Benches.vue, dashboard/src/views/server/Servers.vue, dashboard/src/views/site/Sites.vue, press/api/bench.py, press/api/server.py, press/api/site.py
since users found it a bit of an annoyance in finding their sites
=> fix: remove pagination in site,server,bench list

dashboard/src/components/AlertBenchUpdate.vue, dashboard/src/components/AlertUpdate.vue, dashboard/src/utils.js, dashboard/src/views/bench/Benches.vue, press/api/bench.py, press/api/tests/test_bench.py
=> feat(bench-list): add update available and deploy in progress status

dashboard/src/components/ConfigEditor.vue, dashboard/src/views/bench/BenchConfig.vue, dashboard/src/views/site/SiteConfig.vue, press/api/bench.py, press/api/tests/test_bench.py
And reuse them in both site config and bench config
=> refactor: extract config editor component

press/press/doctype/deploy_candidate/deploy_candidate.py
=> fix: docker build command for apple silicon devices

press/playbooks/roles/mariadb/tasks/main.yml, press/playbooks/roles/mariadb/templates/mariadb-10.6.list, press/playbooks/roles/nginx/tasks/main.yml
- Bumps Mariadb to 10.6
- Adds www-data to frappe usergroup for Nginx
=> Support for Ubuntu 22 for HC

dashboard/src/views/server/NewSelfHostedServer.vue, dashboard/src/views/server/NewSelfHostedServerForm.vue, press/api/selfhosted.py, press/api/server.py, press/press/doctype/ansible_play/test_ansible_play.py, press/press/doctype/ansible_task/test_ansible_task.py, press/press/doctype/database_server/database_server.py, press/press/doctype/plan/test_plan.py, press/press/doctype/security_update_check/security_update_check.py, press/press/doctype/self_hosted_server/self_hosted_server.js, press/press/doctype/self_hosted_server/self_hosted_server.json, press/press/doctype/self_hosted_server/self_hosted_server.py, press/press/doctype/self_hosted_server/test_self_hosted_server.py, press/press/doctype/server/server.py, press/press/doctype/tls_certificate/tls_certificate.py
=> (WIP): BYOD Updates and Patches

dashboard/src/views/bench/BenchConfig.vue, press/api/bench.py, press/api/tests/test_bench.py, press/press/doctype/plan/test_plan.py, press/press/doctype/release_group/release_group.json, press/press/doctype/release_group/release_group.py
- feat(benches): Add dependency table in dashboard
- fix: Parse serialized json in api method
- feat(ReleaseGroup): Set last_dependency_update on dependency update
- test(APIBenchConfig): Show update available on dependency update
- test(APIBenchConfig): Ensure update of dependency keeps setting last_dependency_update
=> Allow editing dependencies from dashboard

press/api/tests/test_site.py, press/press/doctype/agent_job/agent_job.py, press/press/doctype/agent_job/test_agent_job.py, press/press/doctype/remote_file/test_remote_file.py, press/press/doctype/site/site.py, press/press/doctype/site/test_site.py, press/press/doctype/site_domain/test_site_domain.py, press/tests/before_test.py, press/utils/__init__.py
- fix: Raise error instead of logging during tests correctly
- test(RemoteFile): Make site optional arg for util method
- feat(Site): Update apps table based on output from restore jobs
- fix(Site): Clear apps child table correctly
=> feat(Site): Sync installed apps on restore jobs

dashboard/src/views/bench/BenchSites.vue, press/api/bench.py
=> perf(BenchSites): fetch site data all at once and fetch app data when needed

press/press/doctype/marketplace_app/templates/marketplace_app.html, press/templates/marketplace/macros.html, press/www/marketplace/index.html
=> style(Marketplace): follow espresso design

dashboard/src/views/bench/BenchDependencies.vue, press/api/bench.py, press/api/tests/test_bench.py, press/press/doctype/release_group/release_group.py, press/press/doctype/release_group/test_release_group.py
- refactor(ReleaseGroup): Make deploy_information modular
=> fix(Bench): Show text headsup about dependency update

press/agent.py, press/api/tests/test_bench.py, press/fixtures/agent_job_type.json, press/press/doctype/bench/bench.js, press/press/doctype/bench/bench.json, press/press/doctype/bench/bench.py, press/press/doctype/site/test_site.py
- Add a step in Update Bench Configuration job
- Send data in bench_config
- Only updates on Update Bench Configuration job
- Doesn't allow unsetting
Needs https://github.com/frappe/agent/pull/64
=> feat(Bench): Allow setting memory and CPU limits in Bench

codecov.yml, press/press/doctype/bench/bench.py, press/press/doctype/bench/test_bench.py, press/press/doctype/server/server.py, press/press/doctype/site_update/site_update.py, press/press/report/bench_memory_limits/bench_memory_limits.js, press/press/report/bench_memory_limits/bench_memory_limits.json, press/press/report/bench_memory_limits/bench_memory_limits.py
- refactor(Bench): Split up worker allocation code into methods
- fix(Server): Fix math in report
- feat: Add filter in report
=> feat(Bench): Correct report to validate memory limits

dashboard/src/components/AlertBillingInformation.vue, dashboard/src/controllers/account.js, press/api/account.py, press/press/doctype/team/team.py
* if the micro debit for legitimate card verification doesn't work, ask to add some credits
=> fix: Check for a valid payment method to avoid spam

press/press/doctype/bench/bench.py, press/press/doctype/bench/test_bench.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
- feat(Server): Add button to toggle setting memory limits on benches
- feat(Bench): Add parameters to auto set memory limits
=> feat(Bench): Auto set memory limit on benches

dashboard/src/components/global/Badge.vue, dashboard/src2/components/AppSidebar.vue, dashboard/src2/components/JobStep.vue, dashboard/src2/components/NewSiteDialog.vue, dashboard/src2/components/ObjectList.vue, dashboard/src2/components/ObjectListCell.vue, dashboard/src2/objects/bench.js, dashboard/src2/objects/index.js, dashboard/src2/objects/site.js, dashboard/src2/pages/BenchDeploy.vue, dashboard/src2/pages/DetailPage.vue, dashboard/src2/pages/JobPage.vue, dashboard/src2/router.js, dashboard/src2/utils/dayjs.js, dashboard/src2/utils/format.js, press/api/client.py, press/press/doctype/agent_job/agent_job.py, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/release_group/release_group.py, press/press/doctype/site/site.py
- common JobStep component
- routes option to add arbitrary routes for objects
- new site dialog (wip)
=> feat(ui-v2): site jobs and bench deploys

dashboard/src/components/Sidebar.vue, dashboard/src/views/marketplace/MarketplaceApps.vue, dashboard/src/views/server/Server.vue, dashboard/src/views/server/ServerOverviewInfo.vue, dashboard/src/views/server/Servers.vue, dashboard/src/views/settings/EditPermissions.vue, press/api/bench.py, press/api/site.py, press/fixtures/press_method_permission.json
Closes: 
https://github.com/frappe/press/issues/1128
https://github.com/frappe/press/issues/1124
=> feat: Add permissions for servers and marketplace apps

dashboard/src/views/billing/AccountBillingCards.vue, dashboard/src/views/billing/FinalizeInvoicesDialog.vue, dashboard/src/views/settings/AccountProfile.vue, press/api/account.py, press/api/billing.py, press/press/doctype/team/team.py
=> feat: Show a prompt to finalize draft and unpaid invoices before removing all cards or disabling the account 

press/hooks.py, press/press/doctype/team/suspend_sites.py, press/press/doctype/team/team.py, press/templates/emails/unpaid_invoices.html
- Suspend sites of active teams with at least 1 unpaid invoice
- Suspension happens every 3 hours on 10th of each month
=> refactor: site suspension logic

dashboard/src/components/charts/BarChart.vue, dashboard/src/components/charts/LineChart.vue, dashboard/src/components/charts/utils.js, dashboard/src/views/site/SiteCharts.vue, press/api/analytics.py
=> feat(SiteCharts): request count/duration by path bar chart

press/press/doctype/database_server/database_server.js, press/press/doctype/database_server/database_server.py, press/press/doctype/database_server/test_database_server.py, press/press/doctype/server/server.py
- feat(DatabaseServer): Add button to manually adjust memory config
- fix(DatabaseServer): Set ram config as per actually available ram
=> fix(DatabaseServer): Reduce memory related config

dashboard/src/views/site/SiteAlerts.vue, press/api/site.py, press/api/tests/test_site.py, press/press/doctype/press_notification/press_notification.json, press/press/doctype/site_migration/site_migration.py, press/press/doctype/version_upgrade/version_upgrade.py
=> feat(Site): alerts for version upgrades and site migrations

press/playbooks/pkg_exists.yml, press/playbooks/roles/clamav/tasks/main.yml, press/press/doctype/malware_scan/malware_scan.js, press/press/doctype/malware_scan/malware_scan.json, press/press/doctype/malware_scan/malware_scan.py
- fix(MalwareScan): Don't update freshclam after installing clamav
- feat: Add playbook to check if arbitrary package exists
- fix(MalwareScan): Only check clamav installation on creation
=> feat(MalwareScan): Add installed status to report clamav installed

dashboard/src/views/site/SiteChangeGroupDialog.vue, press/api/site.py
Clones the group except 
- team = users's team
- servers = [site's server]
- public = false
=> feat(SiteChangeBench): option to clone the current group

dashboard/src/views/site/SiteChangeRegionDialog.vue, press/api/site.py, press/api/tests/test_site.py
- Displays all regions
- Option to add region when region isn't available in the group
- Move site to the region when it's available
=> feat(SiteChangeRegion): add region option

dashboard/src/components/global/Badge.vue, dashboard/src2/components/ObjectListCell.vue, dashboard/src2/objects/bench.js
=> fix(BenchApps): show badge since there are multiple status

dashboard/src2/components/bench/DependencyEditorDialog.vue, dashboard/src2/objects/bench.js, press/api/bench.py, press/api/client.py, press/press/doctype/release_group/release_group.py
- also add child table fields as valid field
=> refactor(D2-BenchDependencies): fetch dep's version using list resource

dashboard/src2/components/bench/AddRegionDialog.vue, dashboard/src2/objects/bench.js, press/press/doctype/cluster/cluster.py, press/press/doctype/release_group/release_group.py
=> feat(dashboard2): bench region list

dashboard/src2/objects/bench.js, press/press/doctype/release_group/release_group.py
=> refactor(d2-Benches): show status, no. of sites and apps

dashboard/src2/objects/bench.js, dashboard/src2/pages/NewBench.vue, dashboard/src2/router.js
https://github.com/frappe/press/assets/63963181/5621d2b3-0087-4a9d-bc54-68d81e897230
=> feat(dashboard2): new bench

press/press/doctype/team/team.json
This does full table scan otherwise
=> perf: index user on Team doctype

dashboard/src2/components/bench/AddAppDialog.vue
https://github.com/frappe/press/assets/63963181/7897b6da-f335-472e-9bab-925b413efa2e
=> refactor(d2-AddAppDialog): use list view

dashboard/src/views/billing/AccountBilling.vue, dashboard/src/views/billing/AccountBillingPayments.vue, press/press/doctype/team/team.py
=> fix: show amount_due on dashboard

dashboard/src2/components/SiteOverview.vue, dashboard/src2/components/SitePlansCards.vue, dashboard/src2/objects/bench.js, dashboard/src2/objects/site.js, press/api/site.py, press/press/doctype/plan/plan.py, press/press/doctype/site/site.py
=> fix: Site overview

dashboard/package.json, dashboard/src/components/global/Badge.vue, dashboard/src/components/utils/CommitChooser.vue, dashboard/src/components/utils/CommitTag.vue, dashboard/src2/components/GenericList.vue, dashboard/src2/components/bench/UpdateBenchDialog.vue, dashboard/src2/objects/bench.js, dashboard/yarn.lock, press/press/doctype/release_group/release_group.py, press/press/doctype/team/team.py
https://github.com/frappe/press/assets/63963181/a450bdee-ff97-48a1-b699-600fe8d15a10
=> feat(d2): update bench dialog

press/fixtures/press_job_type.json, press/press/doctype/server/server.py
- also MySQLdump config on Server
=> fix(PressJob): Set swappiness on db server on create

press/hooks.py, press/press/audit.py, press/press/doctype/audit_log/audit_log.json
- added new audit methods
- created a new class for partner billing audits
=> feat: new audit methods

press/agent.py, press/press/doctype/optimize_database_query/db_optimizer.py, press/press/doctype/optimize_database_query/optimize_database_query.js, press/press/doctype/optimize_database_query/optimize_database_query.json, press/press/doctype/optimize_database_query/optimize_database_query.py, press/press/doctype/optimize_database_query/test_db_optimizer.py, press/press/doctype/optimize_database_query/test_optimize_database_query.py
This doctype requires you to add:
1. Site name
2. Slow query
Upon creating one, it will run analysis in background and generate
suggested indexes.
depends on https://github.com/frappe/agent/pull/71
=> feat: optimize db query doctype for interactive optimization

press/press/doctype/optimize_database_query/db_optimizer.py, press/press/doctype/optimize_database_query/optimize_database_query.py
Asking frappe to give cardinality for each field is insane amount of
work and potentially full table scans for each column.
Thankfully mariadb already provides this information to reasonable
accuracy in mysql.column_stats - https://mariadb.com/kb/en/mysqlcolumn_stats-table/
Agent PR: https://github.com/frappe/agent/pull/73
=> perf(DBOptimizer): use mysql.column_stats to estimate cardinality

press/fixtures/mariadb_variable.json, press/press/doctype/database_server/database_server.py, press/press/doctype/database_server/test_database_server.py
- chore(MariaDBVariable): Add max_connections and max_user_connections
- fix(DatabaseServer): Reduce buffer pool size (3%)
=> fix(DatabaseServer): Config changes to mitigate oom

press/api/spaces.py, press/docker/Dockerfile, press/docker/config/supervisor.conf, press/press/doctype/bench/bench.json, press/press/doctype/bench/bench.py, press/press/doctype/code_server/code_server.js, press/press/doctype/code_server/code_server.py, press/press/doctype/deploy_candidate/deploy_candidate.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/release_group/release_group.json, press/press/doctype/team/team.json
Enabling adds 30s and 500MB to image build.
https://github.com/frappe/agent/pull/70
=> fix: disable code-server by default

press/hooks.py, press/playbooks/pt_stalk.yml, press/playbooks/roles/pt_stalk/tasks/main.yml, press/playbooks/roles/pt_stalk/templates/pt_stalk.service, press/press/doctype/database_server/database_server.js, press/press/doctype/database_server/database_server.json, press/press/doctype/database_server/database_server.py, press/press/doctype/mariadb_stalk/mariadb_stalk.js, press/press/doctype/mariadb_stalk/mariadb_stalk.json, press/press/doctype/mariadb_stalk/mariadb_stalk.py, press/press/doctype/mariadb_stalk/test_mariadb_stalk.py, press/press/doctype/mariadb_stalk_diagnostic/mariadb_stalk_diagnostic.json, press/press/doctype/mariadb_stalk_diagnostic/mariadb_stalk_diagnostic.py
Uses https://docs.percona.com/percona-toolkit/pt-stalk.html to collect additional diagnostic information when "something weird happens".
By default, the additional information is collected when there are more than 25 running threads, for at least 5 consecutive seconds. We can change this condition later. To avoid becoming an overhead, it waits for 300 seconds before collecting this information again.
The information is dumped in the MariaDB Stalk table.
Needs https://github.com/frappe/agent/commit/94c982306fb0330ef586dc36c6c010d7d9eb76e3
=> feat: Stalk MariaDB with pt-stalk

nginx.conf
closes https://github.com/frappe/press/issues/1294
=> fix: whitelist frappehr.com domain for CSP

press/press/doctype/agent_job/agent_job.js, press/press/doctype/agent_job/agent_job.py
=> feat: provision to pull job status

press/hooks.py, press/press/doctype/alertmanager_webhook_log/alertmanager_webhook_log.py, press/press/doctype/alertmanager_webhook_log/test_alertmanager_webhook_log.py, press/press/doctype/incident/incident.json, press/press/doctype/incident/incident.py, press/press/doctype/incident/test_incident.py, press/press/doctype/incident_settings/incident_settings.json, press/press/doctype/incident_settings_self_hosted_user/incident_settings_self_hosted_user.json, press/press/doctype/incident_settings_self_hosted_user/incident_settings_self_hosted_user.py
=> feat(Incident): Defer calling for auto-resolve

press/press/doctype/site_migration/site_migration.js, press/press/doctype/site_migration/site_migration.py, press/press/doctype/site_migration/test_site_migration.py, press/press/doctype/site_migration_step/site_migration_step.json
- refactor(SiteMigration): Move notification send to separate function
- test(SiteMigration): Add test for activate on failure
- chore(SiteMigration): Add warning about data loss
- fix(SiteMigration): Activate site on failure
- fix(SiteMigration): Handle Delivery Failure cases
=> fix(SiteMigration): Activate site on failure

press/press/doctype/bench/bench.py
- refactor(Bench): Split long archive_obsolete_benches code in parts
fixes #1342
=> fix(SiteMigration): Don't drop destination benches if site is coming

dashboard/src2/components/GenericList.vue, dashboard/src2/components/ObjectListCell.vue, dashboard/src2/components/SiteUpdateDialog.vue, dashboard/src2/components/TabsWithRouter.vue, dashboard/src2/components/bench/UpdateBenchDialog.vue, dashboard/src2/dialogs/ConfirmDialog.vue, dashboard/src2/main.js, dashboard/src2/objects/bench.js, dashboard/src2/objects/site.js, dashboard/src2/pages/DetailPage.vue, dashboard/src2/pages/JobPage.vue, dashboard/src2/pages/LoginSignup.vue, dashboard/src2/pages/NewAppSite.vue, dashboard/src2/pages/ReleaseGroupBenchSites.vue, press/agent.py, press/api/site.py, press/press/doctype/release_group/release_group.py, press/press/doctype/site/site.py, press/press/doctype/site_update/site_update.py, press/press/doctype/team/team.py, press/saas/doctype/saas_product/pooling.py, press/saas/doctype/saas_product_site_request/saas_product_site_request.py
Agent PR: https://github.com/frappe/agent/pull/75
=> fix(d2): create user on trial site

press/hooks.py, press/metrics.py, requirements.txt
Export critical press metrics in Prometheus format
```prometheus
press_builds_suspended 0.0
press_deploy_candidate_totalstatusSuccess 43.0
press_deploy_candidate_totalstatusFailure 26.0
press_site_totalstatusActive 1.0
press_site_totalstatusBroken 1.0
press_site_totalstatusArchived 8.0
press_bench_totalstatusActive 3.0
press_bench_totalstatusArchived 20.0
press_bench_totalstatusPending 1.0
press_bench_totalstatusBroken 21.0
press_server_totalstatusActive 2.0
press_server_totalstatusArchived 11.0
press_database_server_totalstatusArchived 10.0
press_database_server_totalstatusActive 2.0
press_virtual_machine_totalstatusRunning 3.0
press_virtual_machine_totalstatusPending 1.0
press_virtual_machine_totalstatusTerminated 26.0
press_site_backup_totalstatusPending 1.0 …
```
=> feat: Prometheus Metrics

dashboard/src/views/site/Site.vue, dashboard/src/views/site/SiteTransferDialog.vue, dashboard/src2/components/SiteActionCell.vue, dashboard/src2/components/SiteTransferDialog.vue, dashboard/src2/objects/site.js, press/api/site.py, press/press/doctype/site/site.py, press/press/doctype/team_change/team_change.js, press/press/doctype/team_change/team_change.json, press/press/doctype/team_change/team_change.py, press/press/doctype/team_change/test_team_change.py, press/templates/emails/transfer_site_confirmation.html
=> feat(site): transfer site to another team

press/playbooks/roles/prometheus/tasks/main.yml
```
failed to copy: /var/tmp/ansible-tmp-1705319535.679533-47778-255738703771264/source to /home/frappe/prometheus/prometheus.yml
```
=> feat: copy template by running validation and then change the ownership

press/hooks.py, press/press/audit.py, press/press/doctype/site/site.py, press/press/doctype/team/suspend_sites.py, press/press/doctype/team/team.py
- Added new audit method - Active sites with unpaid invoices
- ignored sites on dedicated servers while team suspension
- ignored current month's finalized invoices
- run every day of the month
=> feat: new Audit method

dashboard/src/components/ClickToCopyField.vue, dashboard/src2/components/bench/SSHCertificateDialog.vue, dashboard/src2/objects/bench.js, dashboard/src2/pages/ReleaseGroupBenchSites.vue, press/api/bench.py, press/press/doctype/release_group/release_group.py
Actions
- View in Desk
- Restart
- Rebuild
- Update all sites
- SSH Access
=> feat(d2-BenchSites): bench actions

dashboard/src2/components/site/SiteAppPlanChangeDialog.vue, dashboard/src2/components/site/SiteAppPlanSelectorDialog.vue, dashboard/src2/objects/site.js, dashboard/src2/pages/NewSite.vue, press/api/site.py, press/marketplace/doctype/marketplace_app_plan/marketplace_app_plan.py, press/press/doctype/site/site.py
https://github.com/frappe/press/assets/63963181/5066bd4e-8b8a-4ae2-983e-0047c44db5e9
https://github.com/frappe/press/assets/63963181/e404f8f1-a97a-4741-842a-aa3e8a68aabe
=> feat(d2-Site): app plan selection

dashboard/src2/components/AddTagDialog.vue, dashboard/src2/components/SiteOverview.vue, dashboard/src2/components/settings/profile/AccountProfile.vue, dashboard/src2/objects/bench.js, dashboard/src2/objects/common/tags.js, dashboard/src2/objects/site.js, dashboard/src2/pages/JobPage.vue, dashboard/src2/pages/Settings.vue, press/api/client.py, press/press/doctype/plan/plan.py, press/press/doctype/press_permission_group/press_permission_group.py, press/press/doctype/press_tag/press_tag.py, press/press/doctype/release_group/release_group.py, press/press/doctype/resource_tag/resource_tag.py, press/press/doctype/resource_tag/tag_helpers.py, press/press/doctype/site/site.py, press/press/doctype/team/team.py
=> feat: generic tags ui for site, bench, etc

press/docker/Dockerfile, press/press/doctype/deploy_candidate/deploy_candidate.py
Depends on latest bench to actually work: https://github.com/frappe/bench/pull/1534
In absence of command, nothing will be done.
=> feat: validate frappe-dependencies

dashboard/src2/objects/bench.js, dashboard/src2/objects/site.js, press/api/client.py, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/release_group/release_group.py
- feat: show deployed by columns in deploys list (fixes https://github.com/frappe/press/issues/1413)
- show created_by column in jobs list for both sites and benches (fixes https://github.com/frappe/press/issues/1413)
- fixes https://github.com/frappe/press/issues/1437
1.
2.
3.
=> misc fixes on dashboard-2

press/press/doctype/deploy_candidate/deploy_candidate.py
another reason why pushing fixes in the later hours
of a day is an unsound proposition
=> fix: remove stupid hardcode

press/press/doctype/app/app.py, press/press/doctype/deploy_candidate/test_deploy_candidate.py
set repository owner to workaround workaround
ref: #1465
=> fix: app cache test

press/fixtures/frappe_version.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/test_deploy_candidate.py, press/press/doctype/frappe_version/frappe_version.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/release_group/release_group.json, press/press/doctype/release_group/release_group.py
- fix: bump base bench to 5.22.1
- remove temporary fix
- chore(test): change hrms to raven
=> fix: bump bench to 5.22.1

dashboard/src2/objects/db-server.js, dashboard/src2/objects/server.js, press/api/server.py, press/press/doctype/server/server.py
=> feat(Server): drop server method

press/press/doctype/deploy_candidate/deploy_candidate.js, press/press/doctype/deploy_candidate/deploy_candidate.py
- fix: additional packages skip clause
- feat: add a Check Status button on DC desk
=> fix: additional status check, add Check Status

dashboard/src2/components/SiteActionCell.vue, dashboard/src2/components/site/SiteDatabaseRestoreFromURLDialog.vue, press/press/doctype/site/site.py
=> feat(SiteAction): restore backup with url

press/press/doctype/agent_job/agent_job.py, press/press/doctype/app_release/app_release.py, press/press/doctype/bench/bench.py, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/release_group/release_group.json, press/press/doctype/release_group/release_group.py, press/utils/__init__.py
- fix: toggle use_cached with use_app_cache
- fix: add global delta build flag
- Also remove success check before deploy (more info? commit message!)
=> fix: add global flags, improve error log, etc

dashboard/src/views/site/SiteCharts.vue, press/api/analytics.py
=> feat(SiteCharts): Add avg request duration charts

dashboard/src2/components/GenericList.vue, dashboard/src2/components/NewObjectCell.vue, dashboard/src2/components/site/NewSiteAppSelector.vue, dashboard/src2/pages/NewObject.vue
=> refactor(NewSite): use list view for app selection

press/press/doctype/self_hosted_server/self_hosted_server.py
=> fix: disk validation while setting up the self hosted server

dashboard/src2/components/SiteUpdateDialog.vue, dashboard/src2/components/bench/UpdateBenchDialog.vue, dashboard/src2/utils/dayjs.js, press/hooks.py, press/press/doctype/bench/bench.py, press/press/doctype/site/site.py, press/press/doctype/site_update/site_update.js, press/press/doctype/site_update/site_update.json, press/press/doctype/site_update/site_update.py, press/press/doctype/site_update/test_site_update.py
=> feat(site): schedule site update

dashboard/src2/components/bench/PatchAppDialog.vue, press/press/doctype/deploy_candidate/deploy_candidate.js, press/press/doctype/deploy_candidate/deploy_candidate.py
- fix: skip hrms, cached build breaks something to do with Vite, have not debugged it yet will revert once it is fixed
- fix: UX improvements for App Patch dialog
- chore: disable Check Status, does not work as expected
- chore: validate .patch ext on url
=> fix: quick fixes

press/press/doctype/site_migration/site_migration.py, press/press/doctype/site_migration/test_site_migration.py
But not when site already dropped on source
=> fix(SiteMigration): Cleanup site on destination on failure

dashboard/src2/objects/bench.js, press/press/doctype/release_group/release_group.py
=> feat(BenchDeploys): option to redeploy

dashboard/src2/components/Summary.vue, dashboard/src2/pages/NewServer.vue, dashboard/src2/utils/format.js, press/api/selfhosted.py
https://github.com/frappe/press/assets/63963181/ed8e9e9e-e7ad-493d-8ed3-7237b8838c6d
=> feat(Server): new hybrid server flow

press/api/developer/marketplace.py
Flow:
- Clicked subscribe inside site
- Added billing details
- Added card
- Updated plan
=> feat: Add telemetry for in-site subscription flow

dashboard/src2/components/settings/DeveloperSettings.vue, dashboard/src2/pages/Settings.vue, dashboard/src2/router.js, press/api/account.py, press/api/client.py, press/press/doctype/team/team.py, press/press/doctype/user_ssh_key/user_ssh_key.py
=> feat(Settings): developer settings

press/press/doctype/app_release/app_release.py, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py
- create Press Notification if invalid pyproject.toml
- don't use `sys.exception` cause FC on 3.10
=> fix: handle invalid pyproject as user addressable

.github/helper/install.sh
since we are already using the same in prod
=> ci: use frappe/frappe develop branch

press/exceptions.py, press/press/doctype/site_migration/site_migration.py, press/press/doctype/site_migration/test_site_migration.py
Otherwise there'll be avalanche of err logs
=> fix(SiteMigration): Fail on missing apps in destination

dashboard/src2/components/bench/BenchLogsDialog.vue, dashboard/src2/objects/site.js, dashboard/src2/objects/tabs/site/logs.js, dashboard/src2/pages/LogPage.vue, dashboard/src2/pages/ReleaseGroupBenchSites.vue
=> feat: logs for site and bench

press/press/doctype/subscription/subscription.json, press/press/doctype/subscription/subscription.py, press/press/doctype/usage_record/usage_record.json, press/press/doctype/usage_record/usage_record.py
Co-Authored-By: Rutwik Hiwalkar <rutwikhdev@gmail.com>
=> perf: index usage record date

dashboard/src2/components/bench/AddAppDialog.vue, dashboard/src2/objects/bench.js, press/api/bench.py
fix #1030 
Custom apps can be added from "Add from Github" flow
=> refactor(AddApp): show all marketplace apps

press/api/analytics.py, requirements.txt
fixes #1521
- Also corrects some charts which showed wrong info as they didn't have zerofill (avg, slow queries)
=> refactor: Use elasticsearch-dsl for queries

dashboard/src2/objects/site.js, press/press/doctype/site/site.py, press/press/doctype/site_domain/site_domain.py
=> fix(SiteDomains): row actions

press/press/doctype/usage_record/usage_record.py, press/press/doctype/version_upgrade/version_upgrade.py, press/utils/__init__.py
- fix: defer error log inserts
- fix: invalid log_error call
=> fix: error logging

press/press/doctype/usage_record/usage_record.py, press/press/doctype/version_upgrade/version_upgrade.py, press/utils/__init__.py
=> Revert "fix: defer error log creation"

press/press/report/mariadb_locks_list/mariadb_locks_list.js, press/press/report/mariadb_locks_list/mariadb_locks_list.json, press/press/report/mariadb_locks_list/mariadb_locks_list.py
Using innodb txn and locks table, just dumps it all in single report.
=> feat: See MariaDB locks

dashboard/src2/components/server/ServerLoadAverage.vue, dashboard/src2/components/server/ServerOverview.vue
=> refactor(ServerOverview): minor revamp

dashboard/src2/pages/DetailPage.vue
subscribe to the doc's event instead of doctype
=> fix(DetailPage): subscribe to the doc's events for updates

dashboard/src2/pages/NewServer.vue, dashboard/src2/utils/format.js, press/api/server.py, press/press/doctype/server_plan/server_plan.json, press/press/doctype/server_plan/server_plan.py
=> feat: Premium server plans

dashboard/src2/components/ManageSitePlansDialog.vue, dashboard/src2/components/SitePlansCards.vue, dashboard/src2/components/site/NewSiteAppSelector.vue, dashboard/src2/data/plans.js, dashboard/src2/pages/NewSite.vue, press/api/site.py, press/press/doctype/site/site.py
- Apps are selected first
- Version is auto selected to latest stable version which all selected apps supports
- Region is auto selected to closest region
- rest is the same
=> refactor(NewSite): improved flow

dashboard/src2/components/AlertAddressableError.vue, dashboard/src2/components/AlertBanner.vue, press/press/doctype/deploy_candidate/deploy_candidate.py
- fix: ignore notification if success
- chore: fix component names
=> fix: press deploy notification

press/press/doctype/app_source/app_source.json, press/press/doctype/app_source/app_source.py, press/press/doctype/github_webhook_log/github_webhook_log.py
when an installation:deleted event comes in
set app source to uninstalled, needs to be
handled UI side
=> fix: add GH Webhook event handlers

press/api/app.py, press/api/github.py, press/press/doctype/app_source/app_source.py, press/press/doctype/release_group/release_group.py
- fix: remove invalid app if present on append
- refactor: minor factorization of api.github.app
=> fix: drop app if invalid on RG append

press/press/doctype/user_ssh_key/test_user_ssh_key.py, press/press/doctype/user_ssh_key/user_ssh_key.py
- **fix(UserSSHKey): Throw correct error on adding single word keys**
- **fix(UserSSHKey): Use ssh-keygen for generating fingerprint**
=> fix(UserSSHKey): Improve validation for adding key

press/docker/Dockerfile, press/press/doctype/deploy_candidate/cache_utils.py
ref: https://docs.docker.com/reference/dockerfile/#run---mounttypecache
Setting cache `sharing=locked` should allow only one writer at a time, no mention of reader behaviour, I'm assuming multiple readers, will try this as a possible fix for missing files in _bench app cache_ and _yarn cache_.
=> fix: possible cache fixes

press/press/doctype/site/site.py
=> fix: handle JSONDecodeError on client call

press/templates/marketplace/base.html, press/templates/marketplace/navbar.html
=> fix: Mics marketplace fixes

dashboard/src/components/CardWithDetails.vue, dashboard/src/components/marketplace/MarketplaceAppReviewStages.vue, dashboard/src2/components/marketplace/AppListingStepsDialog.vue, dashboard/src2/objects/marketplace.js, press/api/marketplace.py, press/press/doctype/marketplace_app/marketplace_app.py
=> refactor(MarketplaceApp): add button to sent app for review

dashboard/src2/components/AppSidebarItem.vue, dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/ObjectListFilters.vue, dashboard/src2/data/notifications.js, dashboard/src2/objects/notification.js, dashboard/src2/pages/ListPage.vue, press/api/notifications.py, press/press/doctype/press_notification/press_notification.py
=> feat(dashboard-beta): notifications

press/api/tests/test_bench.py, press/press/doctype/deploy_candidate/test_deploy_candidate.py, press/press/doctype/log_counter/log_counter.py
This reverts commit 412b9e2ebc8fa23b03360c542f5ab8e189aba521.
Also, tries to fix the broken test.
=> Revert "chore(bench-test): skip broken test"

press/fixtures/press_job_type.json, press/playbooks/glass_file.yml, press/playbooks/roles/extend_ec2_volume/tasks/main.yml, press/press/doctype/server/server.py
- **fix(Server): Add playbook for glass for breaking in disk full scenario**
- **fix(Server): Reduce glass file size to 200mb**
- **fix(PressJob): Add glass file on create server**
- **fix(Server): Move short plays to default queue**
=> feat(Server): In case of disk full, break glass

dashboard/src/components/StripeCard.vue, dashboard/src2/components/StripeCard.vue, press/api/billing.py
Internal Ticket ref: https://support.frappe.io/helpdesk/tickets/12161
=> chore: increase micro debit charge to  $1 and 100rs

press/press/doctype/app_source/app_source.py, press/press/doctype/github_webhook_log/github_webhook_log.py
=> fix: reduce release creation errors

dashboard/src2/components/site/SelectSiteForRestore.vue, dashboard/src2/objects/site.js, press/press/doctype/site/site.py, press/press/doctype/site_backup/site_backup.py
=> feat(SiteBackups): restore backup options

dashboard/src2/pages/InstallApp.vue, dashboard/src2/router.js, press/api/marketplace.py
https://github.com/frappe/press/assets/63963181/12fd7af7-f937-43d4-b7db-afb0d56bc7d2
=> feat: install app flow

dashboard/src/views/site/SiteOverviewPlan.vue, dashboard/src/views/site/SitePlansDialog.vue, press/api/client.py
=> fix: addressing a few sentry and other issues

dashboard/src/views/site/SiteCharts.vue, press/api/analytics.py
=> feat(SiteCharts): Add background job charts

press/fixtures/press_job_type.json, press/press/doctype/server/server.py
Reboot is needed for disk change to effect in partition
- Also add nicer doc link in Telegram msg
=> fix(Server): Issue reboot after resizing oci volume

press/api/analytics.py
- **fix(SiteCharts): Don't show backup query in slow logs**
- **fix(SiteCharts): Always show entire timespan in chart**
=> fix(SiteCharts): Make charts easier to read

press/press/doctype/deploy_candidate/deploy_candidate.js, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/docker_output_parsers.py
- Error messages on Fail and Redeploy
- Scheduled builds are failable
- Remove try except from around line parsing
=> fix: more minor build related fixes

press/press/doctype/agent_job/agent_job.json, press/press/doctype/agent_job/agent_job.py
ref: https://github.com/frappe/press/commit/8988c0ef809f5a433358226967e2382a97ac6927#diff-a759c62c1fe1aba1c4267e7a24d90ba6a6e50da5fac78cd584ee564478a239b5L226-L244
=> chore: re-add agent job references

dashboard/src2/objects/marketplace.js, press/press/doctype/marketplace_app/marketplace_app.py
=> feat(MarketplaceApp): delete app in draft state

press/api/site.py
https://letsencrypt.org/docs/caa/
=> feat(SiteDomain): Validate CAA record (if any)

dashboard/src2/components/SiteUpdateDialog.vue, dashboard/src2/objects/marketplace.js
Closes #1635 
Not sure if this is the correct way to do it since I don't know much about Vue/FrappeUI, but seemed logical 😅
=> fix: show app releases in descending order

dashboard/src2/components/settings/RoleConfigureDialog.vue, dashboard/src2/components/settings/RoleList.vue, dashboard/src2/data/session.js, dashboard/src2/pages/NewBench.vue, dashboard/src2/pages/NewServer.vue, dashboard/src2/pages/NewSite.vue, press/patches.txt, press/press/doctype/press_role/patches/change_fields_from_enable_to_allow.py, press/press/doctype/press_role/press_role.json, press/press/doctype/press_role/press_role.py, press/press/doctype/press_role/test_press_role.py, press/press/doctype/release_group/release_group.py, press/press/doctype/server/server.py, press/press/doctype/site/site.py
=> feat(RolePermissions): add site, server and bench creation controls

dashboard/src/controllers/account.js, dashboard/src/views/billing/BillingSummary.vue, dashboard/src/views/onboarding/OnboardingStepSetupPayment.vue, dashboard/src2/pages/BillingOverview.vue, press/api/billing.py, press/api/tests/test_site.py, press/press/doctype/agent_job/test_agent_job.py, press/press/doctype/invoice/invoice.py, press/press/doctype/invoice/test_invoice.py, press/press/doctype/server/server.py, press/press/doctype/site/site.py, press/press/doctype/subscription/test_subscription.py, press/press/doctype/team/suspend_sites.py, press/press/doctype/team/team.py, press/press/doctype/team/test_team.py
This PR removes redundant code which are not used anymore.
- Partner Credits
- Flat Discount related code (we only use discounts for partner)
=> chore: remove flat discount and partner credits code

press/press/doctype/app_release/app_release.py, press/press/doctype/bench/bench.json, press/press/doctype/bench/bench.py, press/press/doctype/deploy_candidate/deploy_candidate.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py, press/press/doctype/deploy_candidate/docker_output_parsers.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/doctype/release_group/release_group.json, press/press/doctype/release_group/release_group.py, press/press/doctype/server/server.py
Metrics Based Changes
- Track manually failed builds
- Track pending duration
- Add handler for module not found
- Add handler for import error
- Add handler for distribution not found
- Add handler for errors during pip install
- Add handler for 2 Vue errors
- Add step for pre-build validations
Non Metrics Based Changes
- remove `job_id` (Deploy Candidate)
- remove `docker_remote_builder_ssh` (Press Settings)
- remove `is_single_container` (Deploy Candidate, Bench)
- remove `is_ssh_enabled` (Deploy Candidate, Bench)
- rename `is_docker_remote_builder_used` to `is_remote_builder_used` (All occurrences)
- rename `docker_remote_builder_server` to `remote_build_server` (All occurrences)
=> fix: improvements from metrics review

press/fixtures/press_job_type.json, press/playbooks/docker_system_prune.yml, press/press/doctype/alertmanager_webhook_log/alertmanager_webhook_log.py, press/press/doctype/prometheus_alert_rule/prometheus_alert_rule.json, press/press/doctype/prometheus_alert_rule/prometheus_alert_rule.py, press/press/doctype/registry_server/registry_server.py, press/press/doctype/server/server.py
- **feat(Server): Add playbook and method to prune docker system**
- **fix(RegistryServer): Suspend builds before pruning**
=> feat: Add press job for pruning docker cache

press/press/doctype/agent_job/agent_job.py
=> Revert "chore: fix object identifier"

press/api/client.py, press/overrides.py, press/press/doctype/agent_job/agent_job.py, press/press/doctype/press_role/press_role.py, press/press/doctype/site/site.json, press/utils/__init__.py
- also add `has_role` method to check if role exists
=> fix: give read access to sites for support agents

dashboard/src2/pages/SetupAccount.vue, press/api/account.py
Removes the required password while setup account via invitation if oauth domain mapping is setup
=> chore: Remove password requirement if oauth domain is setup

press/press/doctype/build_cache_shell/build_cache_shell.py, press/press/doctype/deploy_candidate/deploy_candidate.py
- fix: prevent NoneType attr error
- fix: ensure upload step has correct status
=> fix: dc status issues

press/press/doctype/deploy_candidate/deploy_notifications.py
https://frappecloud.com/docs/common-issues/vite-not-found
=> fix: add UA for vite not found

dashboard/src2/components/site/ConfigureAutoUpdateDialog.vue, dashboard/src2/objects/site.js, press/press/doctype/site/site.py
=> feat(SiteUpdate): add option to configure auto update

dashboard/src2/components/SiteActionCell.vue, dashboard/src2/components/SiteActions.vue, dashboard/src2/components/bench/BenchActionCell.vue, dashboard/src2/components/bench/BenchActions.vue, dashboard/src2/components/server/ServerActionCell.vue, dashboard/src2/components/server/ServerActions.vue, dashboard/src2/objects/bench.js, dashboard/src2/objects/server.js, press/press/doctype/release_group/release_group.py, press/press/doctype/server/server.py, press/press/doctype/site/site.py
=> refactor: grouped actions

dashboard/src2/components/FilterControl.vue, dashboard/src2/components/ObjectListFilters.vue, dashboard/src2/objects/notification.js, press/api/notifications.py
=> refactor(Notifications): `tabButton` for filter and mark all as read option

press/docker/Dockerfile, press/hooks.py, press/press/doctype/app_release/app_release.py, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py
- add retry on redis refused (error 111)
- add yarn build failed UA
- fix pull update failure on dirty repos
- add retry on background job timeout
- retry or fail stuck build and deploy jobs
- catch all UA for repository not found issues
- retry on fail to compute cache key
=> fix: handle more build failure cases

dashboard/src2/components/bench/BenchActionCell.vue, dashboard/src2/objects/bench.js, press/api/bench.py, press/press/doctype/release_group/release_group.py, press/press/doctype/site/site.py, press/press/doctype/team_change/team_change.py, press/templates/emails/transfer_team_confirmation.html
ability to change team of a bench
=> feat(Bench): transfer bench

press/agent.py, press/hooks.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/doctype/site/site.py, press/press/doctype/site_domain/site_domain.py, press/press/doctype/tls_certificate/tls_certificate.json, press/press/doctype/tls_certificate/tls_certificate.py
- Log Certbot and DNS errors 
- Attempt multiple (5 so far) renewals even after failure
- Set correct DNS type on Site domains
- skip_reload on Add Host whenever possible
=> fix: TLS improvements

dashboard/src2/components/StripeCard.vue
=> refactor(Billing): guide user to add another card on certain errors

dashboard/package.json, dashboard/src2/pages/BillingInvoices.vue, dashboard/src2/pages/BillingPaymentMethods.vue, dashboard/yarn.lock, press/patches.txt, press/press/doctype/invoice/invoice.py, press/press/doctype/stripe_payment_method/stripe_payment_method.py, press/press/doctype/stripe_webhook_log/patches/add_payment_method_for_failed_events.py, press/press/doctype/stripe_webhook_log/stripe_webhook_log.json, press/press/doctype/stripe_webhook_log/stripe_webhook_log.py
=> fix(Billing): hint failed payments in invoice and guide them to change payment method

dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/settings/RoleConfigureDialog.vue, dashboard/src2/data/session.js, dashboard/src2/pages/Partners.vue, press/api/account.py, press/press/doctype/press_role/press_role.json, press/press/doctype/press_role/press_role.py
also refactor the `RoleConfigureDialog` to use options api to fix a resource bug
=> feat(RolePermissions): add permission for partner page

press/fixtures/press_job_type.json
=> feat(Server): Add press job to increase swap

dashboard/src2/components/AlertAddressDetails.vue, dashboard/src2/pages/ListPage.vue
=> chore: show address banner to nudge users to complete address details

press/hooks.py, press/press/doctype/incident/incident.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
- Notify about ignored servers daily
=> feat(Server): Convert ignore_incidents checkbox to timestamp

dashboard/src/components/UpdateBillingDetails.vue, dashboard/src2/components/Onboarding.vue
=> fix: make adding billing address details mandatory while onboarding

press/utils/__init__.py
=> fix: remove leading and trailing spaces

press/press/doctype/bench/bench.py, press/press/doctype/site/site.py
- **fix(Site): Don't create on benches being archived**
- **fix(Bench): Set status to pending as soon as it's archived**
- **fix(Bench): Check active sites with for update**
ref: https://support.frappe.io/helpdesk/tickets/13374
=> fix(Site): Don't create on archived (or soon to be archived) benches

dashboard/src2/components/server/ServerOverview.vue, dashboard/src2/objects/server.js, press/fixtures/server_storage_plan.json, press/hooks.py, press/press/doctype/invoice/invoice.py, press/press/doctype/server/server.py, press/press/doctype/server_storage_plan/patches/add_subscription_for_servers_with_additional_disk.py, press/press/doctype/server_storage_plan/server_storage_plan.js, press/press/doctype/server_storage_plan/server_storage_plan.json, press/press/doctype/server_storage_plan/server_storage_plan.py, press/press/doctype/server_storage_plan/test_server_storage_plan.py, press/press/doctype/subscription/subscription.json, press/press/doctype/subscription/subscription.py
https://github.com/frappe/press/assets/63963181/364d7644-befa-40ae-97b2-8fd5262628e3
=> feat(Server): add-on storage

dashboard/src2/pages/BillingInvoices.vue
=> fix(ui): adjust columns widths

dashboard/src2/components/bench/UpdateBenchDialog.vue, press/api/bench.py, press/press/doctype/bench_update/bench_update.py, press/press/doctype/deploy_candidate/deploy_candidate.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py, press/press/doctype/deploy_candidate/utils.py, press/press/doctype/deploy_candidate/validations.py, press/press/doctype/release_group/release_group.py
https://frappecloud.com/docs/common-issues/build-might-fail
=> feat: build restriction

dashboard/src/components/UpdateBillingDetails.vue, dashboard/src2/components/ChurnFeedbackDialog.vue, dashboard/src2/components/InvoiceTable.vue, press/api/account.py, press/press/doctype/press_feedback/press_feedback.json, press/press/doctype/press_feedback/press_feedback.py
=> Billing misc fixes

press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/utils.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
- fix: add use_for_build flag
- fix: add build server selection
=> feat: multiple build servers

dashboard/src2/components/ObjectList.vue, dashboard/src2/objects/site.js, press/press/doctype/site/site.py
fix #1782 
https://github.com/frappe/press/assets/63963181/8b5d2763-9241-4dc0-9628-54b2bab79852
=> feat(SiteDomains): show certbot error in a banner

requirements.txt
=> Fix : get-app fail on Apple Silicon

press/api/notifications.py, press/press/doctype/press_notification/patches/link_reference_doctype_to_notifications.py, press/press/doctype/press_notification/press_notification.json, press/press/doctype/press_notification/press_notification.py
=> fix(notification): apply role permissions on notifications

press/press/doctype/app_release/app_release.py, press/scripts/migrate.py
fixes #1447
The script was not working due to press api changes and other small parsing issues.
=> fix: Fixing migrate-to

dashboard/src2/components/GitHubAppSelector.vue, dashboard/src2/components/NewAppDialog.vue, dashboard/src2/components/bench/AddAppDialog.vue, dashboard/src2/components/marketplace/NewMarketplaceAppDialog.vue, dashboard/src2/objects/marketplace.js, press/api/github.py, press/press/doctype/marketplace_app/marketplace_app.py
=> fix(Marketplace): use separate dialog component for adding apps

press/press/doctype/release_group/release_group.py, press/press/doctype/release_group/test_release_group.py
=> feat: restrict creation of new private benches to servers configured in site plan

press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py
- fix: handle incompatible python version - handle yarn install failed
- fix: retry on gpg key retrieve timeout
- fix: retry on yarn/npm registry failures
- fix: add UA for invalid version string in pip setup
=> fix: grouped fixes from metrics review

dashboard/src2/pages/BillingMarketplacePayouts.vue, press/patches.txt, press/press/doctype/payout_order/patches/change_fields_from_recipient_to_team.py, press/press/doctype/payout_order/patches/compute_total_amount.py, press/press/doctype/payout_order/payout_order.json, press/press/doctype/payout_order/payout_order.py, press/press/doctype/payout_order/test_payout_order.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py
- change label of commission usd rate to usd rate
- show proper currency symbols for net total amount
- add total amount in user's currency
=> refactor(payout-order): change recipient to team

press/press/doctype/site_plan_change/site_plan_change.py
=> Revert "fix: upgrade to usd 5 from other plan's not allowed"

dashboard/src/views/site/SiteCharts.vue, dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue, dashboard/src2/components/site/SitePerformance.vue, dashboard/src2/objects/site.js, dashboard/src2/pages/DetailPage.vue, press/agent.py, press/api/analytics.py, press/api/site.py, press/fixtures/agent_job_type.json, press/press/doctype/app_release/app_release.py, press/press/doctype/site/site.js, press/press/doctype/site/site.py, press/press/doctype/site/test_site.py, press/press/doctype/team/team.json, press/press/doctype/team/team.py, press/press/report/mariadb_slow_queries/db_optimizer.py, press/press/report/mariadb_slow_queries/mariadb_slow_queries.py, press/utils/__init__.py
The below screenshots will give you an idea what this feature is all about.
The ability to create database indexes based on suggested indexes .
=> feat : Query optimization

dashboard/package.json, dashboard/src/views/checkout/CheckoutPlans.vue, dashboard/src2/components/Onboarding.vue, dashboard/src2/main.js, dashboard/src2/pages/NewSite.vue, dashboard/yarn.lock, press/api/account.py, press/api/site.py, press/hooks.py, press/press/doctype/account_request/account_request.py, press/press/doctype/site/site.py, press/press/doctype/team/team.py, press/utils/telemetry.py
**Events -**
- account_request_created
- verification_mail_sent
- verification_mail_read (it uses pixel tracking in mail, in many email clients, this images doesn’t get loaded, so it can give wrong info sometime)
- clicked_verify_link
- completed_signup
- added_card_or_prepaid_credits
- created_first_site
- first_site_status_changed_to_active
- first_site_setup_wizard_completed
**Session Replay -**
- Onboarding Page
- New Site Page (If user hasn't created any site)
=> chore: signup flow funnel

press/agent.py, press/playbooks/roles/update_agent/tasks/main.yml, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/doctype/server/server.py
=> feat: option to add branch in agent_repository

dashboard/src2/pages/NewSite.vue, press/api/marketplace.py, press/api/site.py, press/patches.txt, press/press/doctype/marketplace_app/marketplace_app.json, press/press/doctype/marketplace_app/marketplace_app.py, press/press/doctype/marketplace_app/patches/change_field_from_first_site_creation_to_site_creation.py
- show which apps are not supported in specific version on hover
=> refactor(NewSite): show new site selected apps for public bench

dashboard/src2/objects/bench.js, dashboard/src2/objects/common/jobs.js, dashboard/src2/objects/server.js, dashboard/src2/objects/site.js, press/press/doctype/agent_job/agent_job.py
- also show delivery failure as failure in the list
=> refactor(Jobs): use common agent job object

press/press/doctype/razorpay_webhook_log/razorpay_webhook_log.py
=> fix: dont raise error in rzp authorized handler if payment already captured

press/www/saas/billing.js
make the subscription banner nicer
=> fix(ux): update subscription banner

press/press/doctype/site/site.py
In fewer cases, the flag taking some time to get added after set_value.
In that time, the user is getting redirected to **Administrator** logged in saas site.
=> fix: additional_system_user_created flag sometimes not setting

press/templates/saas/setup-account.html
Fixes https://github.com/frappe/press/issues/2009
=> chore: at saas setup make phone number field as mandatory

deployment/nginx.conf
Fixes https://github.com/frappe/press/issues/2010
=> fix: add frappedesk.com to csp of fc

press/templates/saas/setup-account.html
=> Revert "chore: at saas setup make phone number field as mandatory"

dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue
=> fix: better phrasing of toast message

dashboard/src2/components/DismissableBanner.vue, dashboard/src2/components/ObjectList.vue, dashboard/src2/components/SiteOverview.vue, dashboard/src2/components/SitePlansCards.vue, dashboard/src2/objects/site.js, press/press/doctype/site_plan/site_plan.py
Adds a dismissable banner (7 days) for sites on shared bench
<details>
<summary>Screenshots</summary>
</details>
=> fix(Site): upsell private bench plans for sites on shared bench

dashboard/src2/components/ActiveServersDialog.vue, dashboard/src2/components/settings/profile/AccountProfile.vue, press/api/account.py, press/press/doctype/team/team.py
=> fix: validate active servers before disabling account

press/press/doctype/app_release_approval_request/app_release_approval_request.py
=> fix: do not process commented out line

press/api/marketplace.py, press/patches.txt, press/press/doctype/marketplace_app/patches/convert_images_to_webp.py
stonks while loading images in website or dashboard 📈
=> feat(marketplace): convert all images to webp

dashboard/src2/components/site/SiteChangeBenchDialog.vue, press/api/server.py, press/api/site.py
=> feat: allow select server during bench clone

dashboard/src2/data/session.js, dashboard/src2/router.js, press/api/account.py, press/press/doctype/account_request/account_request.py, press/press/doctype/stripe_payment_method/stripe_payment_method.py, press/press/doctype/team/team.py
- fix the data collection in backend
- in dashboard, identify logged-in user, everytime user visits dashboard
- in dashboard, on logout reset posthog state
=> revamp: posthog data collection

dashboard/src2/objects/marketplace.js, press/press/doctype/app_release/app_release.py
=> feat(ui): show status of code screening

press/press/workspace/press/press.json
=> fix: workspace for press

dashboard/src2/components/AlertAddPaymentMode.vue, dashboard/src2/components/AlertAddressDetails.vue, dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/Onboarding.vue, dashboard/src2/components/OnboardingWithoutPayment.vue, dashboard/src2/pages/ListPage.vue, dashboard/src2/pages/Welcome.vue, dashboard/src2/router.js, press/press/doctype/team/team.py
https://github.com/user-attachments/assets/b335732e-5db5-4fad-905b-584858a36bdc
- allow users to create first site without adding any payment mode
- the usage will be counted in unpaid invoice
=> feat: allow to create first site without payment mode

dashboard/src2/components/marketplace/CodeReview.vue, dashboard/src2/objects/marketplace.js, press/api/client.py, press/press/doctype/app_release_approval_request/app_release_approval_request.py
The UI can be improved.
The next feature is to add a comments option.
https://github.com/user-attachments/assets/e7ce2a06-1503-4d0d-88f9-5c0ca63c0d0d
=> feat: show Code Review screen to Publisher

dashboard/src2/components/AppTrialSubscriptionDialog.vue, dashboard/src2/pages/app_trial/Setup.vue, dashboard/src2/pages/app_trial/Signup.vue, press/saas/doctype/product_trial_request/product_trial_request.py, press/saas/doctype/product_trial_signup_field/product_trial_signup_field.json, press/saas/doctype/product_trial_signup_field/product_trial_signup_field.py
Check https://github.com/frappe/press/issues/2067 for details
=> fix: saas v2 issues #2067

press/auth.py, press/press/doctype/site/site.json, press/press/doctype/site/site.py, press/saas/api/__init__.py, press/saas/api/readme.md, press/saas/doctype/product_trial/product_trial.py, press/utils/__init__.py
Check the `press/saas/api/readme.md` of pull request for details.
Additional -
- Add these internal site config keys
- fc_communication_secret
- subscription
=> feat: auth mechanism for sass site to FC communication

deployment/nginx.conf
=> perf: add more file types to cache

dashboard/src2/components/partners/PartnerApprovalRequests.vue, dashboard/src2/components/settings/profile/AccountPartner.vue, press/api/partner.py, press/partner/doctype/partner_approval_request/partner_approval_request.py
- No duplicate creation of approval requests
- Better UI & UX for Partner approval requests list view
- Partner manager will only be notified after it is approved by partner
=> refactor: partner approval process

dashboard/src2/App.vue, dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/Onboarding.vue, dashboard/src2/components/OnboardingAppSelector.vue, dashboard/src2/components/OnboardingWithoutPayment.vue, press/api/marketplace.py, press/press/doctype/team/team.py
Sidebar will be hidden on this conditions -
- if team has no parent team
- if no sites created
- if no payment mode added
- if team doesn't own any marketplace app
- if team user doesn't part of other team
**App selector re-design:**
- **Desktop View**
- **Mobile View**
=> feat(experimental): hide sidebar for first time user

dashboard/src2/components/DateTimeControl.vue, dashboard/src2/components/SiteUpdateDialog.vue, dashboard/src2/objects/site.js, press/press/doctype/site/site.py, press/press/doctype/site_update/site_update.py
fix #2066 
https://github.com/user-attachments/assets/e5df26ce-3ca9-4a59-a739-4613f719876b
=> feat(SiteUpdate): option to edit and cancel a scheduled update

press/press/doctype/site/saas_site.py, press/www/saas/billing.js
=> Revert "fix: wrong no of trial days in in-desk subscription banner"

dashboard/src2/pages/CreateSiteForMarketplaceApp.vue, dashboard/src2/pages/InstallApp.vue, dashboard/src2/router.js, press/api/client.py, press/api/marketplace.py, press/press/doctype/bench/bench.py, press/press/doctype/site/site.py, press/press/doctype/site_group_deploy/site_group_deploy.js, press/press/doctype/site_group_deploy/site_group_deploy.json, press/press/doctype/site_group_deploy/site_group_deploy.py, press/press/doctype/site_group_deploy/test_site_group_deploy.py, press/press/doctype/site_group_deploy_app/site_group_deploy_app.json, press/press/doctype/site_group_deploy_app/site_group_deploy_app.py
Earlier for apps that aren't present in a public bench or one of your private benches we showed a disclaimer with docs for user to install app to their bench.
Now we can create bench and site together while trying out an app
<details><summary>Screenshots</summary>
</details>
=> feat(Marketplace): create site and bench together for install app

dashboard/src2/components/server/ServerOverview.vue, dashboard/src2/objects/server.js, press/press/doctype/server/server.py
=> feat(Server): configure auto add storage

dashboard/src2/components/settings/RoleConfigureDialog.vue, dashboard/src2/components/settings/TeamSettings.vue, dashboard/src2/data/session.js, dashboard/src2/pages/Settings.vue, press/api/account.py, press/press/doctype/press_role/press_role.json, press/press/doctype/press_role/press_role.py
fix #1984 
- Enables access for billing, apps, partner tab
- Can create new site, bench, server
- Can add team members and configure permissions for them
<details><summary>Screenshot</summary>
</details>
=> feat(RolePermissions): admin roles

dashboard/src2/components/AlertBanner.vue, dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/auth/Configure2FA.vue, dashboard/src2/components/settings/TeamSettings.vue, dashboard/src2/components/settings/TeamSettingsDialog.vue, dashboard/src2/components/settings/profile/TFADialog.vue, dashboard/src2/pages/Enable2FA.vue, dashboard/src2/router.js, press/press/doctype/team/team.json, press/press/doctype/team/team.py
- User won't be able to do any operation on the team 2FA is enforced until they enable it.
- They will be able to switch to other team (that doesn't have 2FA enforced) they're part of and use as normal even if they don't enable it.
=> feat(2FA): option to enforce 2FA team wide

press/press/doctype/team/team.py
for some weird reasons default currency is being set as USD even when the country is India
(not replicable in development setup)
=> fix: set correct currency for new teams

dashboard/src2/pages/saas/Setup.vue, dashboard/src2/pages/saas/Signup.vue, dashboard/src2/pages/saas/in_desk_billing/Invoices.vue, dashboard/src2/pages/saas/in_desk_billing/Onboarding.vue, dashboard/src2/pages/saas/in_desk_billing/Overview.vue, press/api/account.py, press/press/doctype/site/site.py, press/saas/doctype/product_trial_request/product_trial_request.json, press/saas/doctype/product_trial_request/product_trial_request.py
- configure session replay in signup, setup, in-desk billing page
- capture events of product trial request
=> feat: posthog integration in new saas flow

dashboard/src2/components/MarketplaceAppListing.vue
https://trace.frappe.cloud/organizations/frappe/issues/34512/?project=14&query=is%3Aunresolved+setShowIsPublicGithubRepository&referrer=issue-stream&statsPeriod=90d&stream_index=0
=> fix: calling method that does not exist

dashboard/src2/components/site/NewSiteAppSelector.vue, dashboard/src2/pages/NewSite.vue, dashboard/src2/utils/country.ts, press/api/site.py, press/press/doctype/marketplace_app/marketplace_app.json, press/press/doctype/marketplace_app/marketplace_app.py, press/press/doctype/marketplace_localisation_app/marketplace_localisation_app.json, press/press/doctype/marketplace_localisation_app/marketplace_localisation_app.py, press/press/doctype/release_group/release_group.json, press/press/doctype/release_group/release_group.py, press/press/doctype/team/team.json, press/press/doctype/team/team.py
- Marketplace App has localisation apps linked to it with a mapping of country
- When user selects a country for localisation the app wrt the country is installed along with it.
=> feat: option to install localistion app on creating site

dashboard/src2/pages/ReleaseGroupBenchSites.vue, press/press/doctype/bench/bench.py
If someone thinks of a better shape than a star for this, please change it.
=> fix: add tooltip to indicate inplace update

dashboard/src2/components/AddressForm.vue, press/api/account.py, press/press/doctype/team/team.py
Don't allow users to change country from/to India from any foreign countries Such changes leads to accounting issues.
=> fix: raise error when changing address country

press/press/doctype/invoice/stripe_webhook_handler.py, press/press/doctype/payment_dispute/payment_dispute.json, press/press/doctype/payment_dispute/payment_dispute.py
Also enabled Early Fraud Warnings webhook endpoints
=> fix: add status and reason for dispute

dashboard/src2/components/settings/DeveloperSettings.vue, dashboard/src2/components/settings/RoleConfigureDialog.vue, dashboard/src2/data/session.js, press/api/account.py, press/api/client.py, press/api/webhook.py, press/press/doctype/press_role/press_role.json, press/press/doctype/press_role/press_role.py
Added `webhook configuration`, so that team owner can restrict access to this page to other users.
=> feat: add webhook configure permission in press role

press/hooks.py, press/overrides.py, press/press/doctype/invoice/invoice.py
=> fix: allow team members to access invoice pdf

press/press/doctype/team/team.py
Fixes https://github.com/frappe/press/issues/2203
actual changes > https://github.com/frappe/press/pull/2206/files#diff-acd8dae1b11d231c8269d59279ad29b10c855ab22296f9804148c1e0097c8698R916-R927
=> fix: allow to create site if user has paid 2 invoices in past even user has zero prepaid credits

press/press/doctype/razorpay_webhook_log/razorpay_webhook_log.py
=> fix: handle non-fc payments

dashboard/src2/pages/devtools/database/DatabaseSQLPlayground.vue, press/agent.py, press/fixtures/agent_job_type.json, press/press/doctype/agent_job/agent_job.py, press/press/doctype/site/site.py, press/press/doctype/site_database_table_schema/site_database_table_schema.js, press/press/doctype/site_database_table_schema/site_database_table_schema.json, press/press/doctype/site_database_table_schema/site_database_table_schema.py, press/press/doctype/site_database_table_schema/test_site_database_table_schema.py
Agent PR - https://github.com/frappe/agent/pull/141
=> feat(SQLPlayground): move sql schema fetching task to agent job

dashboard/package.json, dashboard/src2/components/devtools/database/SQLResultTable.vue, dashboard/yarn.lock
Fixes https://github.com/frappe/press/issues/2246
=> fix(SQLPlayground): use papaparse for csv generation

dashboard/src2/components/ActiveServersDialog.vue, dashboard/src2/components/ChangePaymentModeDialog.vue, dashboard/src2/components/ChurnFeedbackDialog.vue, dashboard/src2/components/billing/FinalizeInvoicesDialog.vue, dashboard/src2/components/settings/profile/AccountProfile.vue, press/api/account.py, press/press/doctype/team/team.py
Earlier the flow was broken due to validations being ran on a disabled team which is handled by a guard clause now. 
Also refactor a bunch of other non-optimal things.
=> fix: disable account flow

dashboard/src2/components/TabsWithRouter.vue, dashboard/src2/objects/common/apps.ts, dashboard/src2/objects/common/index.ts, dashboard/src2/objects/common/types.ts, dashboard/src2/objects/site.js, dashboard/src2/pages/DetailPage.vue, press/press/doctype/site/site.py
=> feat(Site): show archived sites to users

dashboard/src/components/charts/BarChart.vue, dashboard/src2/components/server/ServerCharts.vue, dashboard/src2/objects/server.js, press/api/server.py
=> feat(ServerAnalytics): request and slow log charts by site

press/utils/billing.py
=> fix: handle network retry

press/api/tests/test_site.py, press/saas/doctype/product_trial/product_trial.py
=> Revert "tests(SiteVersionUpgrade): set a plan on test site to fix issues while comparing cpu_time_per_day"

dashboard/src2/App.vue, dashboard/src2/pages/saas/Login.vue, dashboard/src2/router.js, press/api/account.py, press/api/product_trial.py, press/saas/doctype/product_trial/product_trial.py
> Google OAuth is pending, will be added in future PRs
=> feat(SaaS): seperate login page for saas sites

dashboard/src2/pages/saas/Login.vue, dashboard/src2/pages/saas/OAuthSetupAccount.vue, dashboard/src2/pages/saas/Signup.vue, dashboard/src2/router.js, press/api/account.py, press/api/google.py, press/api/product_trial.py, press/press/doctype/account_request/account_request.py
Related https://github.com/frappe/press/issues/2281
=> feat(saas): google oauth login and signup for new saas flow

dashboard/src2/App.vue, dashboard/src2/data/session.js, dashboard/src2/pages/saas/LoginToSite.vue, dashboard/src2/pages/saas/SetupSite.vue, dashboard/src2/pages/saas/Signup.vue, dashboard/src2/router.js, press/api/google.py, press/api/product_trial.py
Related https://github.com/frappe/press/issues/2281
=>  feat(saas): force account request creation on product trial signup 

press/press/doctype/site/site.py, press/saas/api/site.py, press/saas/doctype/product_trial/product_trial.py
=> chore(saas): misc saas flow fixes and tweaks

press/press/doctype/site/site.py, press/saas/api/site.py, press/saas/doctype/product_trial/product_trial.py
=> Revert "chore(saas): misc saas flow fixes and tweaks"

press/patches.txt, press/press/doctype/drip_email/drip_email.json, press/press/doctype/drip_email/drip_email.py, press/press/doctype/drip_email/patches/set_correct_field_for_html.py
Also add option to let user write the mail content not just in HTML but also in markdow and rich text
=> refactor(drip-email): add option to evaluate condition

dashboard/src2/pages/InstallApp.vue, press/api/marketplace.py
check for standard apps while installing from marketplace without payment mode
=> fix(install-app): check for payment mode added for non standard apps

press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.js, press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.py
Fixes https://github.com/frappe/press/issues/2320
=> fix: mariadb deadlock browser

press/press/audit.py, press/press/doctype/audit_log/audit_log.py, press/tests/test_audit.py
- **fix(BackupRecordCheck): Consider only yesterday's backup specifically**
- **refactor(BackupRecordCheck): Move long queries to methods**
- **fix(BackupRecordCheck): Update tests and fix bugs**
- **fix(BackupRecordCheck): Ignore recently activated sites**
- **fix(BackupRecordCheck): Ignore sites activated today also**
=> fix(BackupRecordCheck): Improve accuracy of audit

dashboard/src2/components/marketplace/NewMarketplaceAppDialog.vue
=> feat(marketplace): Only allow public github repo to be added for marketplace publishing

.cspell.json, .github/hooks/todo-warning.sh, .github/workflows/validate-pr-title.yaml, .pre-commit-config.yaml, commitlint.config.js, package.json, setup-pre-commit.sh, yarn.lock
Run `./setup-pre-commit.sh` locally to set it up.
=> feat: Add cspell and commitlint to pre-commit and ci

press/api/monitoring.py, press/exceptions.py, press/press/doctype/alertmanager_webhook_log/alertmanager_webhook_log.py
- https://trace.frappe.cloud/share/issue/ad9a6a4c51394e3f8671b0b85c995a45/
- https://support.frappe.io/helpdesk/tickets/26981
- refactor(monitoring): implement ruff suggestions
=> fix(alert-manager-webhook-log): Skip creation for disabled alert rules

press/patches.txt, press/press/doctype/subscription/test_subscription.py, press/press/doctype/usage_record/patches/add_unique_constraint.py, press/press/doctype/usage_record/usage_record.py
To avoid duplicate usage record creation
=> fix(usage-record): Add Unique constraints

press/api/account.py, press/api/tests/test_account.py
This will add some basic sanity check for address and reduce invoice creation errors.
Shamelessly copied from https://github.com/resilient-tech/india-compliance/blob/dd73d67fe2c3cb83f8d964270f7cb4da098eb0db/india_compliance/gst_india/utils/__init__.py#L232 
Screenshot:
=> feat(billing): Validate pincode with billing details

dashboard/src2/components/MarketplaceAppListing.vue
Incorrect display of repository visibility.
Temoprarily removed.
=> fix(marketplace): Incorrect display of repository visibility

dashboard/src2/components/MarketplaceAppListing.vue, press/press/doctype/marketplace_app/marketplace_app.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/report/marketplace_app_repository_visibility/marketplace_app_repository_visibility.js, press/press/report/marketplace_app_repository_visibility/marketplace_app_repository_visibility.json, press/press/report/marketplace_app_repository_visibility/marketplace_app_repository_visibility.py
=> feat(marketplace): Prepared report for marketplace-app repo visibility

press/press/doctype/database_server/test_database_server.py, press/press/doctype/incident/incident.json, press/press/doctype/incident/incident.py, press/press/doctype/incident/test_incident.py, press/press/doctype/incident_settings/incident_settings.json, press/press/doctype/incident_settings/incident_settings.py, press/press/doctype/incident_suggestion/incident_suggestion.json, press/press/doctype/incident_suggestion/incident_suggestion.py, press/press/doctype/monitor_server/monitor_server.json, press/press/doctype/monitor_server/monitor_server.py, press/press/doctype/proxy_server/test_proxy_server.py, press/press/doctype/server/test_server.py, press/press/doctype/virtual_machine/test_virtual_machine.py, requirements.txt
- **feat(incident): Identify affected resource for incident**
- **feat(incident): Add problem detection and suggestions**
- **chore(requirements): Add playwright**
- **feat(incident): Take screenshot of Grafana dashboard on confirmation**
- **feat(incident): Take screenshot of relevant instances**
=> feat(incident): Capture relevant information on confirmation

.cspell.json, press/api/account.py, press/press/doctype/press_feedback/press_feedback.json, press/press/doctype/press_feedback/press_feedback.py
Added Team creation and Last paid invoice amount in feedback
=> feat(churn-feedback): Add few more details in feedback

dashboard/src2/components/partners/PartnerOverview.vue
Fixes #2454 
- Before Fix
- After Fix
=> fix(partner-portal): Recalculate tier progress when user change tab

.github/workflows/main.yaml, .pre-commit-config.yaml, dashboard/src2/components/Onboarding.vue, dashboard/src2/pages/SiteLogin.vue, dashboard/src2/pages/saas/LoginToSite.vue, dashboard/src2/pages/saas/SetupSite.vue, press/agent.py, press/api/site_login.py, press/fixtures/agent_job_type.json, press/press/doctype/agent_job/agent_job.py, press/press/doctype/site/site.py, press/press/doctype/site_domain/site_domain.py, press/press/doctype/team/team.py, press/saas/doctype/product_trial/product_trial.py, press/saas/doctype/product_trial_request/product_trial_request.json, press/saas/doctype/product_trial_request/product_trial_request.py
requires https://github.com/frappe/agent/pull/168
=> refactor(signup): Let users have user defined subdomains

dashboard/src2/components/billing/PaymentDetails.vue, dashboard/src2/components/settings/profile/AccountPartner.vue
=> fix(partner): Show the details shared with Partner upon linking

.cspell.json, press/api/email.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py
=> feat(spam-check): Configurable options for Spamd

press/api/analytics.py, press/api/server.py
- Move chart functions to classes
- Add "Other" bucket like in Kibana charts
=> refactor(analytics): Move common chart code to class

dashboard/src2/components/DismissableBanner.vue, dashboard/src2/components/ManageSitePlansDialog.vue, dashboard/src2/components/PlansCards.vue, dashboard/src2/components/SiteOverview.vue, dashboard/src2/components/billing/BillingDetails.vue, dashboard/src2/components/billing/CardForm.vue, dashboard/src2/components/billing/PrepaidCreditsForm.vue, dashboard/src2/objects/common/index.ts, dashboard/src2/objects/common/types.ts, dashboard/src2/pages/ReleaseGroupBenchSites.vue, dashboard/src2/pages/SetupAccount.vue
https://github.com/user-attachments/assets/de998306-9135-46fb-91e3-2a2cefd55018
=> refactor: Let user add payment info on upgrading plan for trial site

dashboard/src2/pages/SiteLogin.vue, press/api/site_login.py
related https://github.com/frappe/frappe/pull/31541
https://github.com/user-attachments/assets/e9228943-0ff3-451d-b18f-e0bf8fcc015d
https://github.com/user-attachments/assets/758f44ae-5a0a-439a-b731-27bb676cc9bd
=> feat: Allow login for specific site from site login page

dashboard/src2/components/server/ServerCharts.vue, dashboard/src2/components/site/SiteAnalytics.vue, press/api/analytics.py
- **refactor(server-charts): Remove unused function**
- **fix(site-charts): Add normalize option to slow query charts**
=> feat(site-charts): Add normalize toggle for slow query charts

dashboard/src2/pages/LoginSignup.vue, dashboard/src2/pages/SetupAccount.vue, press/api/account.py, press/api/site_login.py, press/press/doctype/account_request/account_request.py
https://github.com/user-attachments/assets/472ec2a2-716e-4794-9ed6-dfa37e60c1a2
Also add login attempt tracker for all OTP flows
=> feat(login): Allow users to login via otp

press/hooks.py, press/press/doctype/physical_backup_restoration/physical_backup_restoration.js, press/press/doctype/physical_backup_restoration/physical_backup_restoration.json, press/press/doctype/physical_backup_restoration/physical_backup_restoration.py, press/press/doctype/physical_backup_restoration_step/physical_backup_restoration_step.json, press/press/doctype/physical_backup_restoration_step/physical_backup_restoration_step.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/doctype/site_backup/site_backup.py, press/press/doctype/virtual_disk_snapshot/virtual_disk_snapshot.json, press/press/doctype/virtual_disk_snapshot/virtual_disk_snapshot.py, press/press/doctype/virtual_machine/virtual_machine.py
Fixes https://github.com/frappe/press/issues/2518
Details are in issues description
=> refactor: Make physical restoration flow better

press/press/doctype/drip_email/drip_email.py, press/templates/emails/drip_email.html
=> refactor: Redesign drip email template

press/press/doctype/marketplace_app/patches/change_field_from_first_site_creation_to_site_creation.py, press/runner.py, press/utils/__init__.py
To use https://github.com/frappe/frappe/pull/31719
=> refactor: Don't depend on PyMySQL

press/hooks.py, press/press/doctype/ansible_console/ansible_console.py, press/press/doctype/database_server/database_server.json, press/press/doctype/database_server/database_server.py, press/press/doctype/disk_performance/disk_performance.js, press/press/doctype/disk_performance/disk_performance.json, press/press/doctype/disk_performance/disk_performance.py, press/press/doctype/disk_performance/test_disk_performance.py, press/press/doctype/server/server.py
Record disk latency issues of disk.
If Read or Write latency exceed 9ms, It will be recorded.
=> feat(analytics): Check And Record High Disk Latency

.cspell.json, dashboard/src2/components/NavigationItems.vue, dashboard/src2/components/partners/PartnerCertificateRequest.vue, dashboard/src2/components/partners/PartnerCertificates.vue, dashboard/src2/components/partners/PartnerMembers.vue, dashboard/src2/components/partners/PartnerOverview.vue, dashboard/src2/components/settings/profile/AccountPartner.vue, dashboard/src2/pages/PartnerAdmin.vue, dashboard/src2/pages/PartnerAdminCertificates.vue, dashboard/src2/pages/PartnerList.vue, dashboard/src2/pages/Partners.vue, dashboard/src2/router.js, press/api/client.py, press/api/partner.py, press/partner/doctype/partner_certificate/partner_certificate.js, press/partner/doctype/partner_certificate/partner_certificate.json, press/partner/doctype/partner_certificate/partner_certificate.py, press/partner/doctype/partner_certificate/test_partner_certificate.py, press/partner/doctype/partner_certificate_request/partner_certificate_request.js, press/partner/doctype/partner_certificate_request/partner_certificate_request.json, press/partner/doctype/partner_certificate_request/partner_certificate_request.py, press/partner/doctype/partner_certificate_request/test_partner_certificate_request.py, press/press/doctype/team/team.json, press/press/doctype/team/team.py
------
Team doctype is now more structured (e.g. Partner section contains all details related to Partner)
=> feat(prm): Partner Certification Request

dashboard/src2/components/InvoiceTable.vue, press/api/billing.py
=> feat(invoice): Download Invoice as CSV

press/api/bench.py, press/press/doctype/release_group/release_group.py, press/press/doctype/server/server.py
=> fix: prepare server for generic provider

press/press/doctype/deploy_candidate/deploy_candidate.py, press/saas/doctype/product_trial_request/product_trial_request.py
=> fix: no agent job found

press/press/doctype/site/saas_pool.py, press/press/doctype/site/site.json, press/press/doctype/site/site.py, press/press/doctype/site_backup/site_backup.py, press/press/doctype/site_update/site_update.py
Fixes https://github.com/frappe/press/issues/2564
**Tasks -**
- refactor: Remove Logical Backup as Failover to Physical
- Make the state management better
=> refactor: Remove Logical Backup as Failover to Physical

press/api/callbacks.py
Reducing web worker load enqueuing job payload processing.
=> fix: Reducing work from web worker

press/api/callbacks.py
- Try catch block in job processing
=> fix: Error handling

press/press/doctype/app_source/app_source.py
Support for
required_apps = ["erpnext", "hrms"]
=> fix: Fixes ticket 35744

press/agent.py, press/fixtures/press_webhook_event.json, press/press/doctype/bench/bench.py, press/press/doctype/deploy_candidate/deploy_candidate.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/utils/webhook.py
Fixes: #2570
Working towards adding on start and on end webhooks on deploys.
**Added Events**
- Bench Deploy Status Update
- Bench Status Update
=> feat: Adding deploy candidate webhooks

press/press/doctype/server/server.js, press/press/doctype/server/server.py
Server shows the agent version running.
=> feat(agent): Add utility to show agent version in server

press/playbooks/roles/setup_pyspy/tasks/main.yml, press/playbooks/setup_pyspy.yml, press/press/doctype/server/server.js, press/press/doctype/server/server.json, press/press/doctype/server/server.py
- Added playbook to setup pyspy on Server
=> feat(pyspy): Added playbook for pyspy setup

press/press/doctype/bench/bench.py, press/press/doctype/bench/test_bench.py, press/press/doctype/site/test_site.py
- Not checking memory max on dedicated servers since, there is no mem cap on them.
=> fix(rebuild): Not checking mem max on private servers

dashboard/src2/pages/ReleaseGroupBenchSites.vue, press/press/doctype/bench/bench.py, press/press/doctype/bench/test_bench.py
- Removed rebuild assets option from UI on public server.
- Added elaborate error message incase of low memeory.
=> refactor(rebuild): No rebuild option on public server

dashboard/src2/objects/group.js, dashboard/src2/pages/DeployCandidate.vue, press/agent.py, press/api/client.py, press/hooks.py, press/patches.txt, press/press/doctype/agent_job/agent_job.py, press/press/doctype/app_release/app_release.py, press/press/doctype/bench/bench.json, press/press/doctype/bench/bench.py, press/press/doctype/deploy/deploy.json, press/press/doctype/deploy/deploy.py, press/press/doctype/deploy_candidate/deploy_candidate.js, press/press/doctype/deploy_candidate/deploy_candidate.json, press/press/doctype/deploy_candidate/deploy_candidate.py, press/press/doctype/deploy_candidate/deploy_notifications.py, press/press/doctype/deploy_candidate/docker_output_parsers.py, press/press/doctype/deploy_candidate/test_deploy_candidate.py, press/press/doctype/deploy_candidate/validations.py, press/press/doctype/deploy_candidate_build/deploy_candidate_build.js, press/press/doctype/deploy_candidate_build/deploy_candidate_build.json, press/press/doctype/deploy_candidate_build/deploy_candidate_build.py, press/press/doctype/deploy_candidate_build/patches/migrate_to_separate_build.py, press/press/doctype/deploy_candidate_build/test_deploy_candidate_build.py, press/press/doctype/release_group/release_group.py, press/press/doctype/site/test_site.py
Reverts frappe/press#2635
Made changes to address the performance issues shown below (while running the patch).
=> Revert "Revert "feat(builds): Separate build doctype""

press/press/doctype/deploy/deploy.json
To make updates faster in the while running the patch.
=> perf(migration): Index candidate on deploy

press/press/doctype/deploy_candidate_build/deploy_candidate_build.json, press/press/doctype/deploy_candidate_build/deploy_candidate_build.py, press/press/doctype/deploy_candidate_build/patches/migrate_to_separate_build.py
Stop running builds (after insert) in patch.
=> fix(build): Stop build in patch

press/press/doctype/deploy_candidate/deploy_notifications.py
- Correct press notification linking
=> fix(notifications): Correct doctype and docname

dashboard/src2/pages/DeployCandidate.vue, press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
View in desk (from dashboard) redirection fixed.
=> fix(dashboard): Deploy Candidate Build redirection

press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
Moving glob clean up to deploy candidate build.
=> fix(glob): Loop over files with glob post moving to build

press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
Fixed no force on stop and fail in deploy candidate build
=> fix(stop-and-fail): No force in stop and fail

press/press/doctype/build_metric/build_metric.json, press/press/doctype/build_metric/build_metric.py
Custom datetime for metric generation
=> feat(metric): Add custom datetime to metric generation

press/docker/Dockerfile, press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
Get-pip version support for version < 3.9
=> feat(get-pip): Add support for get-pip version < 3.9

press/press/doctype/build_metric/build_metric.json, press/press/doctype/build_metric/build_metric.py, press/press/doctype/build_metric/build_metric_types.py
Getting median instead of average for durations, and moved to auto increment naming.
=> chore(naming): Auto increment name & median

press/press/doctype/bench/bench.py
Checking build status for process job update instead of candidate status
=> fix(new-bench): Process new bench job update correctly

.cspell.json, press/agent.py, press/fixtures/agent_job_type.json, press/hooks.py, press/playbooks/roles/update_agent/tasks/main.yml, press/press/doctype/agent_update/agent_update.js, press/press/doctype/agent_update/agent_update.json, press/press/doctype/agent_update/agent_update.py, press/press/doctype/agent_update/test_agent_update.py, press/press/doctype/agent_update_server/agent_update_server.json, press/press/doctype/agent_update_server/agent_update_server.py, press/press/doctype/database_server/database_server.json, press/press/doctype/database_server/database_server.py, press/press/doctype/proxy_server/proxy_server.json, press/press/doctype/proxy_server/proxy_server.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
Resolves https://github.com/frappe/press/issues/2660
**Tasks -**
**Screenshots -**
=> feat: Agent update tool

dashboard/src2/components/billing/PrepaidCreditsForm.vue, dashboard/src2/pages/PartnerNewPayout.vue, press/api/regional_payments/mpesa/utils.py
=> fix(mpesa): Enable mpesa for all kenyan users in beta

press/docker/Dockerfile, press/press/doctype/deploy_candidate_build/deploy_candidate_build.js, press/press/doctype/deploy_candidate_build/deploy_candidate_build.json, press/press/doctype/deploy_candidate_build/deploy_candidate_build.py, press/press/doctype/deploy_candidate_build/test_deploy_candidate_build.py, press/press/doctype/press_settings/press_settings.json, press/press/doctype/press_settings/press_settings.py, press/press/doctype/server/test_server.py
=> feat(arm): Facilitate arm builds for associated x86 builds

press/press/doctype/log_server/log_server.json, press/press/doctype/log_server/log_server.py, press/press/doctype/monitor_server/monitor_server.json, press/press/doctype/monitor_server/monitor_server.py, press/press/doctype/registry_server/registry_server.json, press/press/doctype/registry_server/registry_server.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
=> feat: Provision to configure custom ssh user and port on missing doctype

dashboard/src2/components/site/InstallAppDialog.vue
=> fix(marketplace): Skip plan selection if site and app owner is same

press/api/billing.py, press/api/regional_payments/mpesa/utils.py
Fetch and push customers tax_id to the partners site after successfull transaction
=> fix(mpesa): Fetch and push customers tax_id

dashboard/src2/components/site/SiteAnalytics.vue, press/api/analytics.py
- Show detailed charts if prominent generally
fixes #2410
=> feat(site-analytics): Conditionally show detailed charts for certain endpoints

dashboard/src2/pages/NewSite.vue, dashboard/src2/pages/signup/SetupSite.vue, press/api/product_trial.py, press/api/site.py, press/api/tests/test_site.py, press/saas/doctype/product_trial/product_trial.py, press/saas/doctype/product_trial_request/product_trial_request.py, press/utils/__init__.py
Also implements a better cluster detection method (using [Haversine distance](https://en.wikipedia.org/wiki/Haversine_formula)) instead of pinging the servers and comparing the ping time.
requires https://github.com/frappe/agent/pull/211
=> feat: Region specific wild card domains

press/press/doctype/app_source/app_source.py
Ignore commented requried_apps & ignore empty required_app in required_apps list
=> fix(required-apps): Required apps handling

press/api/server.py
Fetch mount point based on server platform and series
=> fix(prometheus): Prometheus mount point

press/agent.py
Ref: https://github.com/frappe/agent/pull/212
=> fix(app-sync): Use raw apps list if already formatted by agent

dashboard/src2/components/partners/PartnerOverview.vue
* Show renew btn 30 days before
=> fix(prm): Add Renewal terms confirmation

press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
- Don't know how or why this was passing locally 🤔 (maybe because no real builds were run)
=> fix(test): Deploy candidate tests

press/press/doctype/server/server.py
When manually adding storage on the database server we end up with the wrong mountpoint in the logs causing misleading emails, this is because of the way dashboard only queries for the application server and not both application and database server.
=> fix(mountpoint): Guess accurate mountpoint for database server as well

press/playbooks/install_cadvisor_arm.yml, press/press/doctype/server/server.py
Couldn't find cadvisor on some arm servers assuming missing cadvisor binary.
=> fix(cadvisor): Fix missing cadvisor in vmi for arm servers

dashboard/src2/components/server/ServerOverview.vue, dashboard/src2/pages/NewServer.vue
=> fix(ui): Fix line height

.cspell.json, press/fixtures/press_job_type.json, press/playbooks/install_and_setup_ncdu.yml, press/playbooks/roles/install_and_setup_ncdu/tasks/main.yml, press/playbooks/server.yml, press/press/doctype/server/server.py
- Install ncdu
- Sudo whitelist ncdu
Ref: https://github.com/frappe/agent/pull/223
=> feat(ncdu): Added ansible play to support ncdu

dashboard/src2/components/StorageBreakupChart.vue, dashboard/src2/components/server/ServerOverview.vue, dashboard/src2/components/server/StorageBreakdownDialog.vue, press/press/doctype/server/server.py
- Added tree component
- Added data transformations
=> feat(storage): Add storage breakdown of app server

press/exceptions.py, press/press/doctype/agent_job/agent_job.py, press/press/doctype/agent_job/test_agent_job.py, press/press/doctype/bench/bench.py, press/press/doctype/bench/test_bench.py, press/press/doctype/site/test_site.py
Refactors archiving of obsolete benches.
=> refactor: Bench archive checks and code

press/press/doctype/release_group/release_group.py
In case of no update in app, select app source, release and hash form the apps in the release group currently and not the last deployed active bench since we want changes to reflect if people update the release group apps.
=> fix(apps-to-update): Select correct app source

press/press/doctype/server/server.py
- Add rules for when we charge users on storage addition
=> chore(subscription): Add checks before creating / updating subscription

.cspell.json, press/api/server.py, press/press/doctype/cluster/cluster.py, press/press/doctype/server/server.py
=> feat: Machine capacity

press/press/doctype/virtual_machine/virtual_machine.py
This PR adds functionality to perform Reboot, Stop, Terminate actions on Hetzner machines.
=> feat: Actions on Hetzner Machines

dashboard/src/components/server/ServerOverview.vue, press/press/doctype/server/server.py
- Make low storage more obvious (another attempt to reduce tickets about storage).
- Show storage increment recommendation from prometheus.
=> Storage recommendation

press/fixtures/press_job_type.json, press/press/doctype/server/server.py
- Setup Ncdu moved to additional config.
- Archive folder setup moved to additional config updated condition if has volume setup the archive folder on volume
=> fix(press-job): Move config to additional config

dashboard/src/objects/server.js, press/api/client.py, press/press/doctype/server_activity/server_activity.js, press/press/doctype/server_activity/server_activity.json, press/press/doctype/server_activity/server_activity.py, press/press/doctype/server_activity/test_server_activity.py, press/press/doctype/virtual_machine/virtual_machine.py
Created log doctype
Collecting Log
Displaying log on the dashboard similar to site activity log
=> feat(server-log): Add server activity log on the dashboard

press/hooks.py, press/press/doctype/server_activity/server_activity.py, press/press/doctype/virtual_machine/virtual_machine.py
Fix permissions to view server activity
=> chore(permissions): Use press overrides

dashboard/src/objects/server.js, press/press/doctype/incident/incident.py, press/press/doctype/server/server.py, press/press/doctype/server_activity/server_activity.json, press/press/doctype/server_activity/server_activity.py
~~Add likely cause post resolution.~~
~~Highlight incidents on the activity log.~~
=> feat(server): Incident log

press/press/doctype/incident/incident.py
In case of unidentified resource fallback to server.
=> chore(incident): Unidentified resource

press/hooks.py, press/press/audit.py
Add vm plan audit to check for discrepancies
=> feat(audit): Vm plan audit

press/press/doctype/audit_log/audit_log.json, press/press/doctype/audit_log/audit_log.py
=> feat(audit-log): Add new audit type

press/incident_management/doctype/incident_investigator/incident_investigator.json, press/incident_management/doctype/incident_investigator/incident_investigator.py, press/incident_management/doctype/incident_investigator/test_incident_investigator.py, press/incident_management/doctype/investigation_step/investigation_step.json, press/press/doctype/incident/incident.json, press/press/doctype/incident/incident.py, press/press/doctype/server/test_server.py
- Limit investigations, added cool off period for same server incidents.
- Ignore self hosted servers
- Updated tests
=> feat(investigator): Investigator additions

press/press/doctype/build_metric/build_metric.py, press/press/doctype/build_metric/build_metric_types.py
- Investigate fc build failures.
=> feat(metrics): Investigate build failures

press/press/report/press_endpoints_audit/press_endpoints_audit.js, press/press/report/press_endpoints_audit/press_endpoints_audit.json, press/press/report/press_endpoints_audit/press_endpoints_audit.py
This PR adds a report to review and analyse press methods
=> feat: Report: press endpoints information

press/infrastructure/doctype/virtual_disk_resize/virtual_disk_resize.py
=> chore(resize): Enqueue long running prerequisites

press/press/doctype/virtual_machine/virtual_machine.py
Related https://github.com/frappe/press/issues/3074
=> refactor(vm): Split OCI Instance syncing in batches

press/press/doctype/site/site.py
Fixes https://github.com/frappe/press/issues/3055
=> fix(site): Check site response before broken->active status change

press/press/doctype/release_group/release_group.py
=> feat(image-size): Show size required for deploy

press/infrastructure/doctype/virtual_disk_resize/virtual_disk_resize.js, press/infrastructure/doctype/virtual_disk_resize/virtual_disk_resize.json, press/infrastructure/doctype/virtual_disk_resize/virtual_disk_resize.py
- Ensure we only trigger once the resize is ready.
- Throw error if there is a mismatch in expected and resolved size.
=> feat(resize): Add ready status to ensure correct trigger point

libs/fcrestore/uploader.go
Sometimes there could be some race condition and that can cancel a uploaded one before calling the complete api
So, its better to not cancel the context
Anyway uploaded files and parts cancelled in a week
=> fix(restore-cli): Don't cancel upload if file already uploaded

press/press/doctype/incident/incident.js, press/press/doctype/incident/incident.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py
https://github.com/frappe/press/commit/36a0acd9a0256a0462e85ba66e8adbe523f8edf9
=> fix(incident): Ignore incidents till instead of since (backport)

dashboard/src/pages/DeployCandidate.vue
=> chore(stop-build): Build failure button

press/hooks.py
At 12 am, all the snapshots started creating
Both bulk operation sometimes cause race issue
Move this bulk snapshot sync to 3am when things get settled
=> refactor: Move bulk snapshot sync to 3am

dashboard/src/pages/signup/LoginToSite.vue
Added some changes in message showing "Complete setup" to "This might take few mins to complete setup"
=> fix(signup): Edit message saying it might take few mins to complete

dashboard/src/pages/signup/LoginToSite.vue
=> Revert "fix(signup): Edit message saying it might take few mins to complete"

press/press/doctype/account_request/account_request.py, press/saas/doctype/product_trial/product_trial.py, press/templates/emails/product_trial_verify_account.html, press/templates/emails/saas_trial.html
This fix is included only for sign up verification email alone for now. Will extend to other emails once this is tested and is working fine in production.
=> fix(mail): Added logo embedding for Sign up verification email

press/press/doctype/database_server/database_server.py, press/press/doctype/server/server.py, press/press/doctype/server/test_server.py
- On Server team change
> - Update server subscription (along with Addon sub)
> - Update db server team
> - Update db server subscription (along with Add on sub)
-  Add validation for different teams in server and db server
=> refactor(server-sub): Update db server sub on server team change

press/playbooks/roles/filebeat/tasks/main.yml, press/press/doctype/bastion_server/bastion_server.js, press/press/doctype/bastion_server/bastion_server.json, press/press/doctype/bastion_server/bastion_server.py, press/press/doctype/bastion_server/test_bastion_server.py, press/press/doctype/database_server/database_server.json, press/press/doctype/database_server/database_server.py, press/press/doctype/proxy_server/proxy_server.json, press/press/doctype/proxy_server/proxy_server.py, press/press/doctype/server/server.json, press/press/doctype/server/server.py, press/runner.py
=> feat: Provision to configure server via bastion host / jump server

press/press/doctype/site/site.py, press/press/doctype/site_database_user/site_database_user.py
This reverts commit 32bb93e767ed4bf3c55a217fcec0cd0ef198b44f.
=> fix: Revert: restrict database users to team owner (#3309)

dashboard/src/components/AddDomainDialog.vue
=> feat(add-custom-domain): Remove scheme and resource path before submit

press/docker/Dockerfile
=> Revert "feat(wkhtmltopdf): Add binaries for jammy"

press/docker/Dockerfile
=> Revert "feat(docker): Pull from ubuntu 22.04"
