dashboard/src/views/SiteOverview.vue

Fixed site showing trial ends in 1 day in site overview even after completing trial.

fix: Site trial end date shown properly in SiteOverview

---

press/hooks.py
press/press/doctype/backup_restoration_test/backup_restoration_test.js
press/press/doctype/backup_restoration_test/backup_restoration_test.json
press/press/doctype/backup_restoration_test/backup_restoration_test.py
press/press/doctype/backup_restoration_test/backup_test.py
press/press/doctype/backup_restoration_test/test_backup_restoration_test.py
press/press/doctype/release_group/release_group.json
press/press/doctype/site/site.py

* Selects a random site from each bench (currently only works for public benches and central bench)
* Creates a new test site with the prefix "brt-" appended.
* Once the test site is successfully created the backup test is marked as a Success.
* A daily clean-up job deletes all test sites created for the backup tests.
* Backup restore test runs once every quarter.

feat: Backup restore test

---

.editorconfig
dashboard/src/components/AppUpdateCard.vue

Github has special URL for showing diff between two commits. While upgrading you
can now click on the tiny arrow to see the diff.
Example URL: https://github.com/frappe/frappe/compare/cadbf91c5874af6b95165d299039cac26eb6cb10..3ec4a618e3a9c56b56c26f11cd76e157dddd3179 
CAUTION / note to reviewer: 
- I do not have local setup, I've edited this totally #YOLO. So please don't trust my vuejs skillz 
- Some styles _might_ be broken since this moves arrow one level down in element tree)
Other changes:
- Added [.editorconfig](https://editorconfig.org/) so contributors don't need to modify their settings when they work on this project. Inline with other frappe projects. Make sure this is okay for you, I only added basic things based on black and prettier settings.

feat: click on compare app update arrow to see diff

---

press/press/doctype/erpnext_site_settings/erpnext_site_settings.py

Earlier `on_update` method used to override the limits value in site_config.
for example:
if there are two keys in limits and only `a` needs to be updated, then `on_update` method overrides entire limits dict
```
limits: {
"a": "x",
"b": "y"
}
```
to
```
limits: {
"a": "x"
}
```
This change will still update keys like users, emails, space etc but won't remove the other keys in limits.

fix: only update required keys in site_config limits

---

dashboard/src/components/AppUpdateCard.vue

2 dots - absolute diff
3 dots - diff assuming it shares a base parent commit somewhere in history. So it shows the commits too.

fix: show proper commit-wise diff [minor]

---

press/press/doctype/site_analytics/site_analytics.json
press/press/doctype/site_analytics/site_analytics.py
press/press/doctype/site_analytics_active/site_analytics_active.json
press/press/doctype/site_analytics_active/site_analytics_active.py

New child table in site analytics which shows the last active timestamp only for enabled system users

feat: new child table for last actives

---

dashboard/src/components/Popover.vue
dashboard/src/views/settings/AccountSSHKey.vue
press/api/account.py
press/api/bench.py
press/press/doctype/user_ssh_key/user_ssh_key.json
press/press/doctype/user_ssh_key/user_ssh_key.py

Users can now Change SSH keys from settings. This action does not edit the existing **User SSH Key** document, instead it creates a new one. 
Added a new field `is_default` in  **User SSH Key** DocType to track the default key for the user. Currently, only the default key is shown in the dashboard. We can show all the added keys as a list later.
When a new key is added, it is set to default and others become non-default.
Fixes: #507 (sort of), #535

feat: Users can change SSH keys

---

dashboard/src/components/StripeCard.vue
dashboard/src/controllers/account.js
dashboard/src/views/billing/AccountBillingCards.vue
press/api/account.py
press/api/billing.py
press/press/doctype/press_settings/press_settings.json
press/press/doctype/stripe_micro_charge_record/stripe_micro_charge_record.js
press/press/doctype/stripe_micro_charge_record/stripe_micro_charge_record.json
press/press/doctype/stripe_micro_charge_record/stripe_micro_charge_record.py
press/press/doctype/stripe_micro_charge_record/test_stripe_micro_charge_record.py
press/press/doctype/stripe_payment_method/stripe_payment_method.json
press/press/doctype/team/team.py
press/utils/billing.py

Many times the cards (payment method) added by the users turn out to be not fit for payment at the end of billing cycle. This can happen due to a variety of reasons, for instance, "This card does not support this kind of transaction" (common), "Non Chargeable", "Insufficient Funds", "Bank Issue", etc. We and the users come to know this only when we try to attempt to charge the card at the end of the billing cycle, leading to **many payment failures.**
This can **hurt both** the users (realizing about the payment failures late leads to site suspension) and us (we have very less confidence on the payment method/card added). 
At the time of adding a card, we will try to charge the card with the **smallest possible amount** (hence, micro) stripe allows (which is $0.50). The **refund** of this …

feat: Micro charges for card testing/confidence

---

press/agent.py
press/fixtures/agent_job_type.json
press/playbooks/primary_proxy.yml
press/playbooks/roles/primary_proxy/tasks/main.yml
press/playbooks/roles/primary_proxy/templates/lsyncd.conf
press/playbooks/roles/primary_proxy/templates/lsyncd.service
press/playbooks/roles/secondary_proxy/tasks/main.yml
press/playbooks/secondary_proxy.yml
press/press/doctype/agent_job/agent_job.py
press/press/doctype/proxy_server/proxy_server.js
press/press/doctype/proxy_server/proxy_server.json
press/press/doctype/proxy_server/proxy_server.py

* Added Provision to setup replica for a proxy server (logic is same as app server)
* Lsyncd is used to sync the proxy configuration files from primary to replica and gets set up on primary on `setup replication`
* Trigger Failover does the following:
- Updates DNS record
- reloads nginx
- updates all app server

feat: proxy replica

---

press/hooks.py
press/press/doctype/invoice_item/invoice_item.json
press/press/doctype/marketplace_app/test_marketplace_app.py
press/press/doctype/payout_order/payout_order.json
press/press/doctype/payout_order/payout_order.py
press/press/doctype/payout_order/test_payout_order.py
press/press/doctype/payout_order_item/payout_order_item.json

At the end of every month, automatically create a **Payout Order** for each marketplace app publisher with items that have been paid (Invoice Items' from Paid Invoices) during this month.
Instead of a due date, Payout Order DocType now has two fields: `period_start` and `period_end` to track the period for which the **Payout Order** was created.
A new field has been added to **Invoice Item** DocType to track whether the item was accounted into a **Payout Order** or not. Invoice Items are marked accounted after the PO has been created that has this item.
The payout order creation job does not create a duplicate for a given period if it already exists.
In summary:

feat: Automate Payout Order Creation

---

press/api/bench.py
press/utils/__init__.py

WARNING: I've not tested this AT ALL as I do not have setup for press.
The main reason for slowness isn't just O(M*N) queries, it's probably just repeated queries.
1. App's repo details can't possibly change during a request so use `db.value_cache` to reuse already queried data.
2. Most deploys share same apps so cache tag info using functools.lru_cache.
This is not safe for other apps but press is single-tenant app so it's fine.
This should convert it to O(M+N) queries which is fine I guess? Converting to single query will require some hackery which I can't do without a proper locla setup.
_Maybe_ closes https://github.com/frappe/press/issues/533

perf: faster versions

---

press/api/server.py
press/press/report/server_stats/server_stats.js
press/press/report/server_stats/server_stats.json
press/press/report/server_stats/server_stats.py

* New Report for having overview of server stats. Currently, it will only display cpu, memory, disk usage in percent.
* Added  a new method in `/api/server.py` to calculate total available resources.

feat: prometheus report for server stats

---

press/press/doctype/bench/bench.py

In some cases, if a update_site_migrate_job is running for a bench, the bench technically has no sites atm and a concurrent archive bench job might trigger successfully without throwing any errors.

fix: validate ongoing jobs before archiving

---

package.json
press/api/developer/marketplace.py
press/press/doctype/marketplace_app/marketplace_app.py
press/press/doctype/site/site.py
press/templates/saas/billing_layout.html
press/templates/saas/macros.html
press/templates/saas/tailwind.config.js
press/www/saas/billing.html
press/www/saas/billing.js

feat: Manage SAAS subscriptions directly from site

---

press/press/doctype/bench/bench.py

There is a chance that site update will fail and move back to old bench will happen. We didn't handle this case before.

fix(Bench): Don't archive bench if update is ongoing from it

---

press/press/report/mariadb_slow_queries/mariadb_slow_queries.py

Adds 3 more useful fields:
- Duration (time taken for query)
- Rows examined and Rows Sent - to guess if too many things are being read but not returned
seems to work fine :eyes:

feat: add more fields in in slow query log report

---

press/press/doctype/team/team.py

on save the `load_doc_before_save` method was called in `on_update` function leading to current doc and not previous one. Thus rename doc was always failing with this:
```
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 50, in application
response = frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 48, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/__init__.py", line 1591, in call
return fn(*args, **newargs)
File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
return func(*args, **kwargs)
File "apps/frappe/frappe/client.py", line 239, in rename_doc
new_name = frappe.rename_doc(doctype, old_name, new_name, …
```

fix: update_billing_details

---

press/press/doctype/site/site_usages.py

Site Usages where not getting updated resulting into incorrect banner on dashboard.

fix(minor): TypeError

---

dashboard/src/components/AlertSiteUpdate.vue
press/agent.py
press/api/site.py
press/press/doctype/site/site.js
press/press/doctype/site/site.py
press/press/doctype/site_update/site_update.json
press/press/doctype/site_update/site_update.py
press/press/doctype/team/team.json

- Check to skip backup from dashboard
- Skip backup from desk
- Dont trigger recover job if site update fails without backup

feat: allow to skip backups

---

press/press/report/binary_log_browser/binary_log_browser.js
press/press/report/binary_log_browser/binary_log_browser.py

Instead of asking user to pick and read one bin log file at a time just use timespan to read data from all files.

feat: Binary log browser using timespan instead of files

---

dashboard/src/components/FileUploader.vue
dashboard/src/components/MarketplaceAppProfile.vue
press/api/marketplace.py
press/press/doctype/team/team.py

- fix(FileUploader): emits message (instead of object) as payload
- feat: add logo image dimensions validation

chore: validate marketplace app image logo dimensions

---

press/press/doctype/version_upgrade/version_upgrade.py
press/scripts/migrate.py

Major Upgrades when skipped can make the whole DB corrupt. Example v12 -> v14 directly shouldn't be done.
- feat: Implement skip Major Upgrades Validation
- fix: Update migrate script to make use of new API

Validation to not skip Major Upgrades Sequentially

---

dashboard/src/components/PrepaidCreditsDialog.vue
dashboard/src/views/settings/AccountTeam.vue
dashboard/src/views/site/Site.vue
press/api/account.py
press/api/saas.py
press/api/site.py
press/patches.txt
press/press/doctype/team/patches/set_team_title.py
press/press/doctype/team/team.json
press/press/doctype/team/team.py
press/utils/__init__.py

1. Parent team's dashboard
2. Child team's dashboard
3.

feat: descriptive lables for child teams

---

press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.js
press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.json
press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.py

A simple report to fetch and view deadlocks on site.
Caution: Written without _proper_ test setup so quite likely doesn't work, but mostly rough edges.
closes #548 
depends on https://github.com/frappe/agent/pull/54

feat: MariaDB Deadlock Browser

---

dashboard/src/views/site/NewSite.vue
dashboard/src/views/site/NewSiteApps.vue
dashboard/src/views/site/NewSiteHostname.vue
dashboard/src/views/site/NewSitePlans.vue
dashboard/src/views/site/NewSiteRestore.vue
press/api/site.py
press/press/report/mariadb_deadlock_browser/mariadb_deadlock_browser.py

Was very slow before because the api was fetching all the release groups owned by the team for filtering on private bench site creation(which was done on UI 😵‍💫). It was also doing pre-fetching of all the info needed for all the steps
Lot of mess in both UI and api in this flow.
Refactor
1. Fetches required info step-wise
2. Only fetches(versions, benches, clusters, apps..) what the UI and flow at the current step needs
3. Bit easier to read and edit
4. Keeping the old apis since they are use in site migration

perf: Refactor new site creation flow

---

press/api/bench.py

Adds back `add_app` api renamed in 2d08aea as it is used in `InstallMarketPlaceApp.vue`

fix: re-add `add_app` api

---

dashboard/src/utils.js
dashboard/src/views/bench/BenchVersions.vue
dashboard/src/views/site/SiteLogs.vue

fix #776 
Timestamps from Agent Job are always in UTC meanwhile timestamps created from desk are localized. So adding an option to `formatDate` to format these timestamps.
This was deployed around 5 mins after 6:59

fix: format agent created timestamps separately

---

dashboard/src/views/site/SiteDatabaseBackups.vue
press/api/site.py

Fix a key error while doing upload and backup.
Reverting (from #861) those lines are safe since config isn't restored anyway (from offsite backups).

fix: key error while restoring site_config_file

---

dashboard/src/components/AlertUpdate.vue
dashboard/src/components/BenchSiteUpdates.vue
dashboard/src/components/SiteUpdateCard.vue
dashboard/src/views/bench/BenchApps.vue
dashboard/src/views/bench/BenchOverview.vue
dashboard/src/views/site/SiteOverview.vue
press/api/bench.py
press/press/doctype/bench/bench.py
press/press/doctype/bench_site_update/bench_site_update.js
press/press/doctype/bench_site_update/bench_site_update.json
press/press/doctype/bench_site_update/bench_site_update.py
press/press/doctype/bench_site_update/test_bench_site_update.py
press/press/doctype/bench_update/bench_update.js
press/press/doctype/bench_update/bench_update.json
press/press/doctype/bench_update/bench_update.py
press/press/doctype/bench_update/test_bench_update.py
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/release_group/release_group.py
press/press/doctype/site/site.py

No need to wait after deploying a bench.
Bench > Update Available > Select apps to update > Select Sites to update.
Fixes: https://github.com/frappe/press/issues/720

feat: Single click bench and site update

---

press/docker/config/supervisor.conf

After this feature of merging and consuming multiple queues w/ feature flag (https://github.com/frappe/press/commit/5016b3b4a98d4cd87836fb31ffb7e15b878a4ddf) now we can go a bit more further and make long worker useful entire day: 
This way now there are two types of workers:
- Dedicated short workers ensuring short-running jobs are quickly consumed. 
- Dedicated long workers for long running jobs which don't have huge expectation for responsiveness.
- Short workers should give higher priority to short and then default jobs.
- Long workers should give higher priority to long jobs as they are only ones to work on long jobs. But when they have free resources they can consume short and default queues too.
- This mix of config ensures that long-running jobs will not block short/default jobs, …

perf: Make long worker consume short and default queue too

---

press/marketplace/doctype/marketplace_app_subscription/marketplace_app_subscription.py
press/marketplace/doctype/marketplace_app_subscription/test_marketplace_app_subscription.py
press/press/doctype/marketplace_app/marketplace_app.py
press/press/doctype/self_hosted_server/self_hosted_server.py
press/press/doctype/site/site.py
press/press/doctype/subscription/subscription.json
press/press/doctype/subscription/subscription.py

Some subscription and invoicing conventions were messed up my this https://github.com/frappe/press/pull/894
This PR follows the same line item convention as the previous usage records and invoices so that we don't have to rewrite every single piece of logic or server script that we have written for "Marketplace App" and not "Marketplace App Subscription"

chore: Create subscriptions such that invoicing conventions are maitained

---

dashboard/src/components/AlertBenchUpdate.vue
dashboard/src/components/AlertUpdate.vue
dashboard/src/utils.js
dashboard/src/views/bench/Benches.vue
press/api/bench.py
press/api/tests/test_bench.py

This reverts commit acad841b675b69af5592df1a2cb7f53bb536898d.
Since it takes a long time to load the list (due to fetching deploy_information for every bench)

revert: add update available and deploy in progress status

---

press/fixtures/frappe_version.json
press/press/doctype/frappe_version/frappe_version.json
press/press/doctype/frappe_version/frappe_version.py
press/press/doctype/frappe_version/test_frappe_version.py
press/press/doctype/frappe_version_dependency/frappe_version_dependency.json
press/press/doctype/frappe_version_dependency/frappe_version_dependency.py
press/press/doctype/release_group/release_group.js
press/press/doctype/release_group/release_group.py
press/press/doctype/release_group/test_release_group.py

fixes: https://github.com/frappe/press/issues/948

refactor: fetch default dependencies from frappe version

---

.github/helper/install.sh
press/api/tests/test_server.py
press/api/tests/test_site.py
press/fixtures/mariadb_variable.json
press/fixtures/press_job_type.json
press/playbooks/roles/mariadb/templates/mariadb.cnf
press/press/doctype/database_server/database_server.py
press/press/doctype/database_server/test_database_server.py
press/press/doctype/database_server_mariadb_variable/test_database_server_mariadb_variable.py
press/press/doctype/mariadb_variable/mariadb_variable.js
press/press/doctype/mariadb_variable/mariadb_variable.json
press/press/doctype/mariadb_variable/mariadb_variable.py
press/press/doctype/mariadb_variable/test_mariadb_variable.py

Checkbox if variable has to be set with default value on new servers. And button to update on existing ones.
New step in create server job for the same

feat: Some method to setting default mariadb variables on servers

---

dashboard/src/views/bench/BenchDependencies.vue

related #1053 
The table looked out of place with what we had so re-using the design from bench config

refactor(BenchDependencies): similar edit flow of Bench Config

---

press/fixtures/press_job_type.json
press/press/doctype/database_server/database_server.json
press/press/doctype/database_server/database_server.py

- feat(DatabaseServer): Add ram field like in server
- fix(APISite): Allow protected methods to be called non request contexts
- fix(PressJob): Autoset memory related variables on server resize

fix(PressJob): Set Mariadb config automatically on resize

---

dashboard/src/components/AlertSiteUpdate.vue
dashboard/src/components/SiteAppUpdates.vue
press/api/site.py

Fixes #1087 from client side
Also reverts https://github.com/frappe/press/commit/a59b398154fd15b346532e30ddbc06e4465a5407

fix(SiteUpdate): filter apps installed in the site in client side

---

press/press/doctype/agent_job/test_agent_job.py
press/press/doctype/bench/bench.py
press/press/doctype/site_update/site_update.py
press/press/doctype/site_update/test_site_update.py

This feature was broken since 925612f69. Needs 2 fixes:
- Reallocate workers only after bench field is set on site
- Bench.workload should consider Pending and Updating sites

fix(SiteUpdate): Correctly update bench workers after site update

---

press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/press_settings/press_settings.json

Note: The user running Press needs to have root access to the remote host over SSH

feat: Build images on a remote docker host 

---

press/press/doctype/app_source/app_source.py

If `repository_url` ends with `".git"` then `repository` is set as `"[REPO_NAME].git"`.
This causes:
- GitHub API call to fail with a `"Not Found"`.
- `last_github_poll_failed` to be set to `False`.
- Renders the App Source broken unless `fetchLatestAppUpdate` is called from the dashboard
- App Release to silently not be created (`AppSource#create_release` is called on insert, silently fails).
- `ReleaseGroup#create_deploy_candidate` to fail with an `apps` mandatory error.
- Frustration.

fix(AppSource): remove `.git` from repo url

---

press/press/doctype/bench/bench.json
press/press/doctype/bench/bench.py
press/press/doctype/bench/test_bench.py

- refactor(Bench): Use 1 query to get values instead of 4
- fix(Bench): Consider memory used by redis and others in memory allocation
- feat(Bench): Add checkbox to skip memory limits optionally

fix(Bench): Redo math for memory limit calc

---

press/docker/config/supervisor.conf

Problem:
- Prerequisite: long running reqeust is going on.
- `bench restart` is requested.
- supervisord sends sigterm to gunicorn master process.
- gunicorn passes it to all child workers and waits for graceful shutdown (30 seconds)
- supervisord has no chill, and sends sigkill to master process in 10 seconds
- gunicorn master proesss is dead, so now child workers will keep running until they complete request which can take a really long time.
- This entire time the sites will be down.
Fix:
- Explicitly encode default graceful_timeout in config - 30 seconds.
- Make supervisor wait 10 more seconds for gunicorn to do its thing, then only send sigkill.
Detailed analysis: https://gameplan.frappe.cloud/g/engineering/projects/152/discussion/2523

fix: Prevent Gunicorn child workers hangup

---

press/press/report/aws_instance_pricing/aws_instance_pricing.json
press/press/report/aws_instance_pricing/aws_instance_pricing.py

- Only shows C (compute optimized), M (general purpose), and R (memory optimized) instance types
- Only shows machines that don't have any special capability e.g. d (instance store), n (enhanced networking, z (extra memory), e (extra storage)
- Shows instance types from all clusters if no cluster is selected
- Removed Enhanced Networking and Instance Store filter
- Added Generation and Latest Generation columns
Before
After

refactor: AWS Instance Pricing Report

---

press/press/doctype/stripe_payment_method/stripe_payment_method.py

Some teams had payment mode empty while their default payment method was set
So this is a potential fix

fix: set `payment_mode` as card if `default_payment_method` is set

---

press/press/doctype/agent_job/agent_job.py
press/press/doctype/agent_job/test_agent_job.py
press/press/doctype/code_server/code_server.py
press/press/doctype/site/site.py

Problem:
For activities that have multiple agent jobs on different servers (Rename Site), when processing the respective callbacks parallelly can leave the doc in a pending state. This happens as the select isn't done with for_update.
Solution:
- ~~Use for_update for every select in the callback transaction.~~ (2nd point ensures serializability as callback will run only after commit of the other)
- Get lock on resource (common to both jobs) at the beginning of the transaction (before the first set_value actually) to avoid deadlock
Essentially simulate [this](https://mariadb.com/kb/en/set-transaction/#serializable)

fix: Serialize agent job callbacks without deadlock

---

dashboard/src/components/BuyPrepaidCredits.vue
press/api/billing.py
press/press/doctype/invoice/fixtures/stripe_payment_intent_succeeded_webhook.json
press/press/doctype/invoice/invoice.json
press/press/doctype/invoice/invoice.py
press/press/doctype/invoice/test_invoice.py
press/press/doctype/press_settings/press_settings.json
press/press/doctype/team/team.py

GST is added to total on validate. Not adding any separate fields for tracking amount before GST since we generate invoices on frappe.io where gst is added as inclusive of total amount.

feat: Add GST for indian customers while finalizing invoices and buying prepaid credits

---

dashboard/src/controllers/account.js

Since most partners now use Prepaid Credits or Card for Billing we can safely remove the validation unless their payment mode is **Partner Credits** or **Paid By Partner**.
PS: Partner Credits will be dropped eventually in coming months.

fix: don't check billing info for paid by partner

---

press/playbooks/roles/mariadb_systemd_limits/templates/memory-custom.conf
press/playbooks/roles/mariadb_systemd_limits/templates/memory.conf
press/press/doctype/database_server/database_server.json
press/press/doctype/database_server/database_server.py
press/press/doctype/database_server/test_database_server.py

- feat: Add MemorySwapMax setting to mariadb memory.conf
- feat(DatabaseServer): Add memory_swap_max field
- feat(DatabaseServer): Set memory_swap_max to 100M by default

feat(DatabaseServer): Limit swap space for mariadb

---

press/press/doctype/team/team.py

Problem:
The methods that handles invoice creation for prepaid credit times out. But we do create an invoice and allocate amount. 
https://github.com/frappe/press/blob/fd266750425d827f207e5563f3a2724b821ca7ed/press/press/doctype/team/team.py#L994
After a while stripe tries to resend webhook until it gets `200 success response`. This creates multiple allocations for the same payment attempt.
This change doesn't crate a duplicate invoice/allocation and simply returns if the amount has been allocated in previous timed out webhook for the same payment_intent/attempt

fix: Handle stripe webhook timeout

---

press/press/doctype/team/team.py

Enabled partner privileges fails for new customers (with no invoice)

fix: don't create invoice if new customer

---

press/telegram_utils.py

Accept positional arguments to telegram execute commands
```
server f6.local.frappe.dev execute increase_disk_size
```
is equivalent to
```
frappe.get_doc("Server", "f6.local.frappe.dev").increase_disk_size()
```
Now, you can pass positional arguments, so
```
server f6.local.frappe.dev execute increase_disk_size 30
```
is equivalent to 
```
frappe.get_doc("Server", "f6.local.frappe.dev").increase_disk_size(30)
```

feat: Positional arguments to execute commands

---

press/press/doctype/balance_transaction/balance_transaction.py
press/press/doctype/balance_transaction_allocation/balance_transaction_allocation.json
press/press/doctype/invoice/test_invoice.py

Problem:
- Purchase 10$ credit (+ve balance transaction)
- Transfer 5$ (-ve balance transaction)
- Create and finalize a 10$ invoice
- Invoice gets finalized even though the team had only 5$ credit left
- Also balance becomes -5$ after the invoice is finalized

fix: negative balance in credit transfer cases

---

dashboard/src/views/site/Site.vue
dashboard/src/views/site/SiteChangeServerDialog.vue
press/api/site.py
press/api/tests/test_site.py

1. Select server they want to move to (user's team should own it)
2. Add server to the bench if it's not added
3. Migrate to the server if it's added

feat(SiteChangeServer): allow switching to different server without creating a new group

---

dashboard/src/views/general/AgentJobs.vue
press/agent.py
press/fixtures/agent_job_type.json
press/hooks.py
press/press/doctype/agent_job/agent_job.json
press/press/doctype/agent_job/agent_job.py
press/press/doctype/agent_job_step/agent_job_step.json
press/press/doctype/agent_job_type/agent_job_type.json
press/press/doctype/deploy_candidate/deploy_candidate.py

- In many cases, we have observed jobs remain in the Undelivered state, 
- Some identified reasons
- The agent on the actual server is not reachable
- The configurations are not proper
- The site or bench does not exist on the actual path
To handle these cases, added a provision, where the system will retry the undelivered job.
While retrying it will check for
- If the job is already delivered to the agent but failed while processing the response
- If not it will retry the job with exponential backoff till it reaches to max retry count
In the Agent Job,  have introduced a new status Delivery Failure. After reaching the max retry count the system will set the agent job status as  Delivery Failure, this will be the final state.

Retry undelivered jobs based on request status

---

press/docker/config/supervisor.conf
press/press/doctype/bench/bench.json
press/press/doctype/bench/bench.py
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/release_group/release_group.json
press/press/doctype/release_group/release_group.py

Allow configuring worker type on release group:
- Sync or unspecified - Synchronous workers handling 1 request per
process at a time.
- gthread - Each process having specified numbers of threads. Each
process can handle same number of requests as thread at same time.
This worker type requires configuring thread count per worker. IMO 2-4
threads per worker seem to give best outcome.
Note: Python GIL limitation applies so concurrency is ONLY for I/O
and non-python CPU work.
- gevent - Green threads which patches low level IO libraries to
magically implement cooperative scheduling.
In general:
- Sync is safe and well tested.
- Gthread is largely safe but there can be some thread unsafe code which
has possibility of breaking
- Gevent is completely untested and requires some modification …

feat: configurable gunicorn worker types

---

press/press/doctype/agent_job/agent_job.py

Framework is oversmart and adds ifnull assuming these fields are nullable, they are not. 
This results in full table scan of agent job, if we just drop ifnull it uses index and doesn't scan anything. 
```sql
select `name`, `server`, `server_type`
from `tabAgent Job`
where `tabAgent Job`.`status` = 'Undelivered' and `tabAgent Job`.`job_id` = 0.0 and `tabAgent Job`.`retry_count` >= 1.0 and coalesce(`tabAgent Job`.`next_retry_at`, '0001-01-01 00:00:00.000000') <= '2023-12-06 17:53:30.404813' and coalesce(`tabAgent Job`.`job_type`, '') in ('')
order by `tabAgent Job`.`modified` DESC
```

perf: optimize agent job retry code

---

press/press/doctype/bench/bench.json
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/release_group/release_group.json

Gevent is not supported, enabling it would break FF (See #1218)
Gevent requires custom implementation of Locals using `gevent.ContextVars` (amongst other things), just replacing usage of ContextVards doesn't work either, probably due to werkzeug `LocalProxy` usage.

chore: remove gevent from Worker Type

---

press/docker/config/supervisor.conf
press/press/doctype/bench/bench.json
press/press/doctype/bench/bench.py
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/release_group/release_group.json
press/press/doctype/release_group/release_group.py

Threads was previously readonly on Bench. Changing it from the Release Group caused updates to supervisor.conf and subsequently the Docker image.
Since agent has its own supervisor.conf, it's better to just update worker count there since that's what's used in prod. This allows on the fly changing of thread count (similar to worker count) using an agent job.
In colab with https://github.com/frappe/agent/pull/69

refactor: set threads as bench config

---

press/press/report/mariadb_slow_queries/mariadb_slow_queries.js
press/press/report/mariadb_slow_queries/mariadb_slow_queries.py

Slow query report has a lot of noise, what's really required is:
1. Which are the slowest queries in a given timeframe sorted by duration/count/rows read etc
2. Which fields are likely unindexed.
Because slow query log is just plain queries it's not that helpful for getting bigger picture of problems and focusing on most important slow queries.
This PR adds "normalize queries" checkbox in this report which instead of showing individual slow queries first normalizes them. Normalizing right now is very DUMB:
- We strip all literal/variables and replace them with `?`
- We format entire query so it's always same in string representation
- For variable length user input like `IN (x, y, z)` we just strip it manually to only put one placeholder there like `IN (?)`
This seems to get the job done …

feat: DBOptimizer p1 - Normalized slow query report 

---

press/press/report/mariadb_slow_queries/mariadb_slow_queries.py
press/utils/db_optimizer.py
press/utils/tests/test_db_optimizer.py
requirements.txt

This PR adds a dumb SQL analyzer to find all potential indexes that can benefit a slow query.
As of this PR the table stats need to be manually fed into the optimizer, subsequent PRs will use agent to automatically fetch this data. WIP: https://github.com/frappe/agent/pull/71
Towards https://github.com/frappe/press/issues/1265

feat(DBOptimizer): p2 - Query analysis

---

press/press/doctype/alertmanager_webhook_log/alertmanager_webhook_log.py
press/press/doctype/incident/incident.py
press/press/doctype/incident/test_incident.py
press/press/doctype/incident_updates/incident_updates.json
press/press/doctype/press_settings/press_settings.json
press/press/doctype/press_settings/press_settings.py
press/press/doctype/press_settings/test_press_settings.py

- Incident creation in bg job
- Handle RetryError correctly
- Disallow duplicate/parallel incident creation
- Reduce threshold for sites down to 15
- Make calls actually sequential
- API Key auth for twilio
- Send telegram msg in after insert of AlertmanagerWebhookLog
- Press Settings won't be reset by create_test_press_settings anymore
- Cleaner tests

fix(Incident): Minor fixes to incident management

---

dashboard/src/components/ChangePaymentModeDialog.vue
press/press/audit.py

Teams were able to select Paid by Partner mode even though their account was not linked to any partner

fix: show paid by partner mode after partner linked

---

dashboard/src/views/server/Server.vue
press/api/server.py
press/press/doctype/account_request/account_request.py
press/press/doctype/stripe_webhook_log/stripe_webhook_log.py

"Visit in desk" button redirects to server doctype for database servers as well since it was hardcoded. 
Fetch server type to redirect to correct server doctype in desk

fix: fetch server type for server path

---

press/press/doctype/balance_transaction/balance_transaction.json

Unallocated amount and Allocated to table should not be allowed to edited after submit manually.

fix: don't allow unallocated amount to be edited

---

press/exceptions.py
press/press/doctype/server/server.py
press/press/doctype/site/site.py
press/press/doctype/site_migration/site_migration.py

Ignore card setup if consultant does site migration
- Separate exception for CannotChangePlan
- Move misplaced install_earlyoom method to Server controller
- Property to check if server is shared

fix(SiteMigration): Handle failure during change plan

---

press/docker/.vimrc
press/docker/Dockerfile
press/press/doctype/deploy_candidate/deploy_candidate.py

Adds a bare-bones `.vimrc`. This enables a few niceties. Some of them:
- sensible tab behavior and display
- line numbers, cursor position display
- syntax highlighting
Some it is from: https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim
And some of it has been suggested by Ankush.

feat: add simple vimrc to image

---

press/docker/config/supervisor.conf
press/press/doctype/bench/bench.json
press/press/doctype/bench/bench.py
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/release_group/release_group.json

Worker pool consumes 70% less memory for maxed out config of 8 background workers. This is roughly **100GB** of reduced RAM usage across FC servers assuming current usage. (Assuming at least 20MB reduction per worker for each bench with >2 workers) 
This is experimental right now but I've not seen any problems with it so far. We can slowly roll this out in future, starting with internal sites.
Note:
- RQ WorkerPool is only a good idea if you need more than 2 workers. At 2 workers it just breaks even.
- This feature is only available in v15.0.0+
Framework: https://github.com/frappe/frappe/pull/21482
Agent: https://github.com/frappe/agent/pull/78

feat: feature flag for RQ WorkerPool support

---

dashboard/src2/components/ConfigPreviewDialog.vue
dashboard/src2/components/ObjectList.vue
dashboard/src2/objects/bench.js
dashboard/src2/objects/site.js

- Adds a config preview dialog
- Adds `secondaryAction` to `ObjectList`

feat: config preview for bench and site

---

debugging/mariadb.build.Dockerfile
debugging/mariadb.build.md
press/playbooks/roles/mariadb_10_6_16_frappe/tasks/main.yml
press/playbooks/upgrade_mariadb_patched.yml
press/press/doctype/database_server/database_server.js
press/press/doctype/database_server/database_server.py

Build and Host patched MariaDB (10.6.16 + https://github.com/MariaDB/server/commit/bb511def1d316ffbdd815f2fc99d0a5813671814) at https://packages.frappe.cloud/mariadb/10.6
To avoid the recurring downtimes apply the patch from https://github.com/MariaDB/server/pull/2866 https://jira.mariadb.org/browse/MDEV-32371

fix: Install patched MariaDB packages from packages.frappe.cloud

---

press/docker/Dockerfile

This automatically optimizes few things:
- dev dependencies are not installed
- minified build

fix: set node environment to production

---

press/press/doctype/site_update/site_update.json

When duplicating site update, these details should be re-fetched. 
Especially job names are not valid for copied site update.

fix: Add no-copy to various site update fields

---

press/press/doctype/deploy_candidate/deploy_candidate.py

- Allows all python files through unless they're a `setup.py`.
- Disallows `js`, `html`, `css` files unless they're in `www` or `public`
- Flips default to `True` (aggressive 😤)
- Disallows few blacklisted files and types (they require dep install or build)

fix: make pull update check more aggressive

---

press/fixtures/frappe_version.json
press/press/doctype/agent_job/agent_job.py
press/press/doctype/frappe_version/frappe_version.py
press/press/doctype/press_settings/press_settings.json
press/press/doctype/release_group/release_group.py

- fix: prevent no len of None
- fix: add sensible message if missing apps
- chore: bump bench version for frappe nightly and v15 (addresses https://github.com/frappe/press/issues/722)
- feat: press settings flags for app cache

fix: add flags, validations, error messages

---

press/api/github.py

closes https://github.com/frappe/press/issues/1455
handles most cases I can think of:
`'title'`
`"title"`
`"title's"`

fix: allow single and double quotes for app_title

---

press/press/doctype/bench/bench.py

`ReleaseGroup.deploy_information` checks last deployed Bench's app's release and hash, so if a Delta Build occurred Bench is not updated with the latest release and hash, this PR fixes that.

fix: set pullable rel and hash on bench

---

press/api/tests/test_site.py
press/press/doctype/agent_job/agent_job.py
press/press/doctype/site/site.py

Add a force check in process_restore_job_update so that apps table
always gets synced.
Required in case where Add Site to Upstream job gets processed first
(and site status is Active by the end of New Site from Backup callback)
leaving process_restore_job_update useless.
Also fixes test to simulate both jobs' success

fix(Site): Update apps table on new site from backup 100% of the time

---

press/press/doctype/site/site.py

Comical chain of events:
1. Site has pause_scheduler: 0 (number)
2. FC syncs this as is - sets it to site config with number `0`.
3. When UI editor edits this *somehow* it gets treated as string and
`"0"` is casted to `Boolean` because site config key master thinks
this has to be boolean.

fix: javascript type madness

---

dashboard/src/components/ConfigEditor.vue
dashboard/src2/components/ConfigEditorDialog.vue
dashboard/src2/objects/bench.js
press/api/bench.py
press/api/site.py
press/patches.txt
press/patches/v0_7_0/set_password_config_type.py
press/press/doctype/common_site_config/common_site_config.json
press/press/doctype/common_site_config/common_site_config.py
press/press/doctype/release_group/release_group.py
press/press/doctype/site/site.py
press/press/doctype/site_config/site_config.json
press/press/doctype/site_config/site_config.py

fix #1469
Introduces `Password` type to both Site Config and Common Site Config
Users will be able to set, edit (won't be able to see the value) and delete the key

feat(config): password/secret support

---

press/press/doctype/release_group/release_group.json

should not set "default" : {} for Table fieldtype
it will cause issue on form rendering, when it try to assign indexing for grid rows
Error Trace was:
grid.js:470 Uncaught (in promise) TypeError: Cannot create property 'idx' on string '{'
at Pt.render_result_rows (grid.js:470:7)
at Pt.refresh (grid.js:432:8)
at frappe.ui.form.ControlTable.refresh_input (table.js:125:13)
at frappe.ui.form.ControlTable.refresh (base_control.js:140:9)
at frappe.ui.form.Layout.attach_doc_and_docfields (layout.js:472:59)
at frappe.ui.form.Layout.refresh (layout.js:334:8)
at frappe.ui.form.Form.refresh_fields (form.js:666:15)
at form.js:610:16

fix: Release Group form rendering bug fix

---

press/press/doctype/app_release/app_release.py
press/press/doctype/deploy_candidate/deploy_candidate.py

Possible fix for issue 10510:
```
[Errno 2] No such file or directory: '/home/frappe/repos/APP_NAME/APP_SOURCE/APP_RELEASE'
```
for when the error is due to a missing `setup.py`
Second commit addresses issue 10509.
For more context on both, visit the issues.

fix: ensure setup.py exists before app_name check

---

press/docker/Dockerfile
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/deploy_candidate/deploy_candidate.py

Individual apps can mention apt dependencies in their pyproject.toml.
[For Example](https://github.com/frappe/drive/commit/83254c0833211613fc4bbe6d50f8801b41c806fa):
```toml
[deploy.dependencies.apt]
packages = [
"ffmpeg",
"libsm6",
"libxext6",
]
```
For each app, these are grouped together into a single package row.
Todo:

feat: fetch deps from app pyproject

---

press/press/doctype/deploy_candidate/deploy_candidate.js
press/press/doctype/deploy_candidate/deploy_candidate.py

Adds 2 actions to Deploy Candidate DocType if `dev_server`:
- Generate Build Context: only generates build context, i.e. skips build.
- Build without push: skips pushing to Docker registry.

fix(dev): add skip build, skip push

---

.github/workflows/main.yaml

This PR adds a CI step to delete some unused files to prevent out of space errors. The app cache test has a disk utilization of ~6GB, this often caused space to run out.
Disk Utilization during app cache tests:
```
Total space: 72.5 GB
- before app cache test: 64.95 GB
- after app cache test:  71.22 GB
- before app cache test: 55.99 GB
- after app cache test:  62.26 GB
```

chore: free up CI space

---

dashboard/src2/objects/site.js
dashboard/src2/pages/ReleaseGroupBenchSites.vue
press/press/doctype/press_notification/test_press_notification.py
press/press/doctype/release_group/release_group.py
press/press/doctype/site_app/site_app.py

fix: add app patch indicators

---

press/press/doctype/ansible_console/ansible_console.py
press/press/doctype/deploy_candidate/deploy_candidate.py
press/utils/__init__.py

Probably the lazy way to go about it. On checking mysql error logs, no particular pattern was found that would help debugging the `InterfaceError` that occurs when build status is set to _Failure_ after a long running build failing.
I'd previously suspected that the connection is killed off, but the wait time out is 8 hours, and so this seems implausible. 
Looking at the build in question, it was failed just cause it was long running (by the server script).

fix: reconnect on build_failed error

---

press/press/doctype/site_update/site_update.py

Evaluating upgradability of 1000s of sites is too much. We can do it as we iterate over available sites to be upgraded.

perf: lazily evaluate upgradability of sites

---

press/press/doctype/team/team.py

- `name` is never null
- In both queries name is from primary table in join, so it's definitely
not null.

perf: remove usage of ifnull

---

press/press/doctype/bench_shell/bench_shell.json

- Add boldly worded message to dissuade unless needed

chore: set default save_output to 0

---

press/agent.py
press/press/doctype/agent_job/agent_job.json
press/press/doctype/agent_job/agent_job.py
press/press/doctype/agent_job_step/agent_job_step.py

Dropped modified index from `Agent Job` and `Agent Job Step`, we don't need these indexes and since these are two most busy tables the index causes unnecessary lock contention. 
TODO:

perf: drop modified index to reduce contention

---

press/press/doctype/app_source/app_source.json
press/press/doctype/app_source/app_source.py
press/utils/__init__.py

Create release adds a comment on failing and doesn't handle non success error codes correctly. Also the function itself is a bit unwieldy.
This PR:
- mentions app source on the error log
- shows error logs on the app source
- factorizes `create_release` into sensible chunks
- removes creating a comment on errors
- handles non success GitHub API call

refactor: refac create_release to suck less

---

press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/docker_output_parsers.py
press/press/doctype/press_notification/press_notification.py

Fixes a few issues in: https://github.com/frappe/press/pull/1631

fix: flush output even on fail

---

dashboard/src/views/bench/BenchApps.vue
dashboard/src2/objects/bench.js

Changed from https://frappecloud.com/docs/faq/custom_apps#why-does-it-show-attention-required-next-to-my-custom-app- to https://frappecloud.com/docs/faq/app-installation-issue
The second page is updated with another potential cause and accounts for recent changes.

chore: change Attention Required URL

---

press/api/github.py

Fixes this:
```
File "apps/press/press/api/github.py", line 218, in app
app_name, title = getapp_name_and_title_from_hooks(
File "apps/press/press/api/github.py", line 270, in getapp_name_and_title_from_hooks
if files and "hooks.py" not in files or "patches.txt" not in files:
TypeError: argument of type 'NoneType' is not iterable
```

fix: conditional causing NoneType iterable error

---

dashboard/src2/dialogs/ConfirmDialog.vue
dashboard/src2/main.js
dashboard/src2/objects/site.js
press/api/client.py
press/press/doctype/site/site.py

https://github.com/frappe/press/assets/63963181/a22fba98-b349-4c9e-bb27-0328ab02401b
- add `setValue` override in client.py
- assign default values if available in confirmDialog

feat(SiteActivity): update notify mail action

---

dashboard/src2/components/NewAppDialog.vue

Repo URL was being set using app name, this is an issue because:
- App name: directory name that contains `hooks.py`
- App title: title in `hooks.py`
This changes repo URL to be set from the selected GitHub repository, only if it isn't found the app name is used to set the repo URL.

fix: set repo url from selected repo

---

dashboard/src2/components/BuildError.vue
dashboard/src2/components/FoldStep.vue
dashboard/src2/components/JobStep.vue
dashboard/src2/pages/BenchDeploy.vue
press/agent.py
press/docker/Dockerfile
press/press/doctype/agent_job/agent_job.py
press/press/doctype/build_cache_shell/build_cache_shell.js
press/press/doctype/build_cache_shell/build_cache_shell.json
press/press/doctype/build_cache_shell/build_cache_shell.py
press/press/doctype/build_cache_shell/test_build_cache_shell.py
press/press/doctype/deploy_candidate/cache_utils.py
press/press/doctype/deploy_candidate/deploy_candidate.js
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/docker_output_parsers.py

**Changes**
- Improves error logging:
- Agent Job doesn't fail on build fail
- Build output reaches press, no need to go to check agent logs
- <details><summary>Displays error up top if parse-able</summary>
</details>
- <details><summary>Adds Build Cache Shell</summary>
</details>
_Note: This remote builder too is tentative, it's usable but will be separated out from press and agent and handled more elegantly._
Agent: https://github.com/frappe/agent/pull/98
Continuation: https://github.com/frappe/press/pull/1631

refactor: remote builder (continuation #1631)

---

press/api/tests/test_bench.py
press/hooks.py
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/docker_output_parsers.py
press/press/doctype/log_counter/log_counter.js
press/press/doctype/log_counter/log_counter.json
press/press/doctype/log_counter/log_counter.py
press/press/doctype/log_counter/test_log_counter.py

A tentative DocType to track Error Log counts, will mostly be removed once Error Log counts are in control.
Can be extended to keep count of other values too by adding entries here:
```python
RECORD_FOR: dict[str, str] = {
"Error Log": "method",
}
```
This is required cause Error Logs are dumped every 10 days, hence counts can't be captured from before that.
There are probably better ways to go about this, but that isn't important for now.

feat: add log counter

---

press/press/doctype/proxy_server/proxy_server.py
press/press/doctype/site/site.py
press/press/doctype/site_backup/site_backup.py
press/press/doctype/site_domain/site_domain.py
press/press/doctype/site_update/site_update.py

1. `process_new_site_job_update`: if any dependent job or all jobs remain undelivered set status to broken
2. `process_restore_job_update`: as job has not delivered set site status to Active
3. `process_reinstall_site_job_update`: as job has not delivered set site status to Active
4. `process_migrate_site_job_update`: as job has not delivered set site status to Active
5. `process_install_app_site_job_update`: as job has not delivered set site status to Active
6. `process_uninstall_app_site_job_update`: as job has not delivered set site status to Active
7. `process_new_site_job_update`: if any dependent job or all jobs remain undelivered set status to broken
8. `process_archive_site_job_update`: if any dependent job or all jobs remain undelivered set status to broken
9. …

feat: handle agent jobs callbacks for delivery failure status

---

press/api/bench.py
press/api/site.py
press/api/tests/test_bench.py
press/docker/Dockerfile
press/press/doctype/app_release/app_release.py
press/press/doctype/bench_update/bench_update.py
press/press/doctype/deploy_candidate/deploy_candidate.js
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/deploy_notifications.py
press/press/doctype/deploy_candidate/test_deploy_candidate.py
press/press/doctype/deploy_candidate/utils.py
press/press/doctype/deploy_candidate/validations.py
press/press/doctype/release_group/release_group.py

Note Merging this PR, will address remaining ToDos in the next one.

fix: minor-ish improvements to deploy_candidate.py

---

press/fixtures/frappe_version.json
press/press/doctype/deploy_candidate/test_deploy_candidate.py
press/press/doctype/frappe_version/frappe_version.py

https://github.com/frappe/bench/pull/1555

chore: bump default bench from 5.22.1 to 5.22.6

---

press/press/doctype/app_release/app_release.json
press/press/doctype/app_release/app_release.py
press/press/doctype/bench/bench.py
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/deploy_notifications.py
press/press/doctype/deploy_candidate/validations.py
press/press/doctype/release_group/release_group.py
press/utils/__init__.py

Continuation of https://github.com/frappe/press/pull/1735
- ~~[ ] JavaScript (?)~~
Set of changes commented out below (can't be see). Will be addressed in the next PR.

fix: minor-ish improvements to Deploy Candidate (Pt.2) (misleading title)

---

dashboard/src2/pages/BenchDeploy.vue
press/press/doctype/deploy_candidate/deploy_candidate.js
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/deploy_notifications.py
press/press/doctype/deploy_candidate/docker_output_parsers.py
press/press/doctype/deploy_candidate/validations.py
press/press/doctype/server/server.py
press/utils/__init__.py
press/utils/jobs.py

These will be addressed in the next PR:

fix: more build related improvements

---

press/press/doctype/invoice/invoice.py

Ideally total of the invoice should never be updated. (will refactor it in another PR)
This PR fixes the issue when the `amount_due` is 0 but still invoice remains unpaid. Its because the amount due is actually not 0 but very very small decimal.

fix: don't update total if no discounts applied

---

dashboard/src2/components/SiteUpdateDialog.vue

Could also change this to: "If the update fails, rollback will not occur"

fix: grammar on site update dialog

---

press/press/doctype/site/site.py

`site.plan` is a **Site Plan**, not a **Plan**.
https://github.com/frappe/press/blob/d1bbf473487914c6c8564180290bf191b0eaba0b/press/press/doctype/site/site.json#L346-L352

fix(Site): Fix deactivate action using Plan instead of Site Plan

---

press/hooks.py
press/press/doctype/alertmanager_webhook_log/alertmanager_webhook_log.py
press/press/doctype/audit_log/audit_log.py
press/press/doctype/malware_scan/malware_scan.py
press/press/doctype/payment_dispute/payment_dispute.py
press/press/doctype/press_settings/press_settings.py
press/press/doctype/security_update_check/security_update_check.py
press/press/doctype/team/team.py
press/press/doctype/telegram_message/telegram_message.js
press/press/doctype/telegram_message/telegram_message.json
press/press/doctype/telegram_message/telegram_message.py
press/press/doctype/telegram_message/test_telegram_message.py
press/telegram_utils.py

Use TelegramMessage as a queue to accept messages and send them out with a  scheduled job.
- Takes care of Telegram rate limits. (Retries sending message after fixed backoff).
- Prioritizes older messages over newer and High-priority messages over low-priority.
replaces
```python
Telegram().send(message=message)
```
with
```python
TelegramMessage.enqueue(message=message)
```
Resolves https://trace.frappe.cloud/organizations/frappe/issues/10775

feat(telegram): Telegram Message DocType to queue message

---

dashboard/src2/pages/BillingInvoices.vue

Earlier "Pay Now" button was only visible for Card invoices where `stripe_invoice_url` is set. 
With this change it will also be visible to Prepaid Credit invoices so users can pay directly from invoice page and finalize the invoice after credits allocated.
Better fix of https://github.com/frappe/press/pull/1743

feat: show Pay Now btn for both card & prepaid credits Inv

---

press/hooks.py
press/press/doctype/deploy_candidate/deploy_candidate.py

Cause remote jobs run remotely, the the output processing is a bit wack rn, their status might not always match what's happened. Hence this job. Will probably remove it later.

fix: add correct_false_positives hook

---

press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate/deploy_notifications.py

For failures that occur during the build, they were just being handled if the build occurred locally.
This fixes that and a few other things.

fix: handle during remote build failures

---

dashboard/src2/router.js

These routes are required for loading the checkout dialog inside the iframe in site for subscription flow

fix: Add routes for iframe checkout screens from old dashboard routes

---

press/agent.py
press/hooks.py
press/press/doctype/agent_job/agent_job.py
press/press/doctype/agent_request_failure/agent_request_failure.js
press/press/doctype/agent_request_failure/agent_request_failure.json
press/press/doctype/agent_request_failure/agent_request_failure.py
press/press/doctype/agent_request_failure/test_agent_request_failure.py
press/press/doctype/bench/bench.py
press/press/doctype/database_server/database_server.py
press/tests/test_agent.py

In case of broken communication with the Agent, prevent cascading failures and error-log spam by 
1. Throttling Agent jobs. Let them sit in the queue (status = Undelivered). 
2. Preventing other requests
- Politely by checking `should_skip_requests` before attempting requests
- Forcefully by throwing AgentRequestSkippedException
These are likely sources of errors
- Broken network
- Broken TLS
- Agent down (502 Bad Gateway on /agent)
- Overloaded/Frozen server (Slow responses on /agent/ping)
Note: Even a single failure will trigger this throttling.
Track the failures in `Agent Request Failure` with the first traceback/error, and failure_count. Removing this entry will let agent requests through (and attempt job delivery).
A scheduled job (every minute) will remove these entries if we get …

feat: Throttle agent requests if we see request failures

---

dashboard/src2/components/NavigationItems.vue
dashboard/src2/data/session.js

Due to this [feature](https://github.com/frappe/press/pull/1874) partner tab was visible for all users.

fix: only allow partners and users with allow_partner role

---

dev-requirements.txt
press/agent.py
press/playbooks/failover_prepare_primary_proxy.yml
press/playbooks/failover_remove_primary_access.yml
press/playbooks/failover_up_secondary_proxy.yml
press/playbooks/fetch_frappe_public_key.yml
press/playbooks/roles/agent/tasks/main.yml
press/playbooks/roles/secondary_proxy/tasks/main.yml
press/playbooks/secondary_proxy.yml
press/press/doctype/cluster/test_cluster.py
press/press/doctype/database_server/test_database_server.py
press/press/doctype/proxy_server/proxy_server.js
press/press/doctype/proxy_server/proxy_server.py
press/press/doctype/proxy_server/test_proxy_server.py
press/press/doctype/root_domain/root_domain.py
press/press/doctype/server/server.py
press/press/doctype/server/test_server.py
press/press/doctype/site/test_site.py

- **fix(Agent): Setup should check for defined sentry_dsn also**
- **fix(ProxyServer): Ensure primary's frappe public key exists before replication**
- **fix(ProxyServer): Update failover method for additional things to be done**
- **perf(TestDatabaseServer): Remove unnecessary wraps**
- **fix(ProxyServer): Correct dns update query**
- **test(ProxyServer): Add test for proxy failover**

fix(ProxyServer): Correct actions required for proper failover

---

dashboard/src2/pages/ListPage.vue
press/api/client.py
press/press/doctype/dashboard_banner/dashboard_banner.js
press/press/doctype/dashboard_banner/dashboard_banner.json
press/press/doctype/dashboard_banner/dashboard_banner.py
press/press/doctype/dashboard_banner/test_dashboard_banner.py

will be shown in sites, benches and server pages

feat: dashboard banner

---

press/press/doctype/razorpay_webhook_log/razorpay_webhook_log.py

Example of notes attr in valid payload
```
"notes": {
"Description": "Order for Frappe Cloud Prepaid Credits",
"Team (Frappe Cloud ID)": "test@example.com",
"gst": 245
},
```

fix: silently skip non-fc razorpay orders

---

press/api/saas.py
press/config/press.py
press/saas/doctype/saas_app/saas_app.py
press/saas/doctype/saas_app_plan/saas_app_plan.py
press/saas/doctype/saas_app_subscription/saas_app_subscription.py

It looks like previously `Plan` doctype was changed to `Site Plan`
But in code in some places, it's still query the db with `Plan` doctype which raises error in local setup.
https://github.com/frappe/press/blob/9020665ac008ea7e8bd4d82fd76463f9ffa93c2e/press/patches/v0_7_0/rename_plan_to_site_plan.py#L4-L8

fix: rename `Plan` to `Site Plan` in all places

---

press/press/doctype/team/team.py

fix: handle 'NoneType' object has no attribute 'strip'

---

press/api/site.py

Sites created through SaaS flow,, it has a option to subscribe to a plan from desk. 
This uses a different api to fetch plans and upgrade to a plan. This can allow users to choose this tiny plan. That's now disabled. This plan will not be shown in desk now.

fix: don't show tiny plan in product trial subscription plans

---

press/press/doctype/site/site.py

Ticket - 18767
In case of standby sites, plan name is not provided. In that case it should pick bench which is available for normal plan.

fix: in _set_latest_bench if plan is not selected assume it's normal plan

---

press/press/doctype/app_release/app_release.py
press/scripts/migrate.py

In addition to local site migration, you can pass external backup file paths..
That way you do not need to restore the site, to migrate it to FC.
The accepted files are validated using mime-types similar to FC frontend

feat : Migrate script external files

---

dashboard/src2/pages/InstallApp.vue
press/api/marketplace.py

**Changes -**
- Auto-check subdomain availability
- Out of the app plans, by default select the first plan (user can then change it to other)
- Exclude tiny plan and it's release groups from the public/private bench and subscription_plan suggestion in `press.api.marketplace.get_install_app_options` api

fix: marketplace install app flow

---

dashboard/.prettierignore
dashboard/index.html
dashboard/package.json
dashboard/src2/main.js
dashboard/yarn.lock

Instead of using the official posthog SDK from npm registry, use the posthog snippet to fetch the library from api server and use that. Else there can be conflict between client SDK version and posthog server version

fix: posthog session replay

---

dashboard/src2/components/Onboarding.vue
dashboard/src2/pages/NewSite.vue

Related **DASHBOARD-V2-3W8**
The error may be thrown when posthog js SDK is not correctly loaded for any reason (can be network issue, or posthog server issue). After this changes, posthog will try to do session recording/capturing only if posthog is loaded successfully.

fix: posthog start session recording error

---

press/api/site.py

Sentry Issue ID - DASHBOARD-V2-3D9
In Sentry, the error has been grouped with other issues.
Actual error - "/api/method/press.api.site.get_site_plans ProgrammingError" 
---
https://github.com/frappe/press/blob/27e2972d204ef40ae045ba869c85064fbfacc9a1/press/api/site.py#L721-L728
On line 728 , in the query builder, it has a where clause to check record in plan names.
In some cases, if the plan list is empty > (), this sql statement become invalid.
That has been fixed in this PR with a guard clause (don't run the query if site plan list is already empty).

fix: api.site.get_site_plans ProgrammingError DASHBOARD-V2-3D9

---

press/api/tests/test_site.py
press/press/doctype/marketplace_app/marketplace_app.py
press/press/doctype/site/site.py

- **refactor(Site): Split up marketplace app install stuff**
- **fix(Site): On restore, process marketplace hooks for apps changed**
- **refactor(Site): Add set_apps method**
- **test(Site): Add tests for marketplace app hooks on restore job**
- **fix(Site): Only Install/Uninstall marketplace hooks for free apps**

fix(Site): Run marketplace hooks for free apps on backup restore

---

dashboard/src2/components/AlertBanner.vue
dashboard/src2/components/NewAppDialog.vue
dashboard/src2/components/bench/AddAppDialog.vue
dashboard/src2/objects/bench.js
dashboard/src2/objects/marketplace.js
press/api/app.py
press/api/bench.py
press/press/doctype/app/app.py
press/press/doctype/deploy_candidate/test_deploy_candidate.py
press/press/doctype/release_group/release_group.py

Allow updation of an App's Source if the app already exists on the bench. Not cleanly separated from Add App, but should allow users to switch to custom `frappe` should they choose to do so.
docs: https://frappecloud.com/docs/benches/custom-app#updating-app-source

feat: allow changing source if app is same

---

press/press/doctype/site/site.py

In current logic `created_first_site`, `first_site_setup_wizard_completed` can also invoked, when the user has old team account and he has no active site in his account. While creating new one, these events can invoked.
Now, we will only capture these events, if the team has only single site regardless of status and team has been created through FC signup.

fix: site creation posthog event capture

---

press/press/doctype/deploy_candidate/validations.py

Fixes https://github.com/frappe/press/issues/2085

fix: add missing doctype paramter to deploy candidate validation

---

dashboard/src/components/Form.vue
dashboard/src2/pages/app_trial/Setup.vue
press/saas/doctype/product_trial/product_trial.json
press/saas/doctype/product_trial/product_trial.py
press/saas/doctype/product_trial_request/product_trial_request.py

Now, in saas signup setup page, we can configure select fields for showing timezone.
Need to append `_tz` suffix to the fieldname and fieldtype should be Select.
- In browser, it will show the timezone list + try to auto-select the timezone based on browser's configuration
- Added validation for select fields and timezone

feat: add timezone field support in saas setup page

---

press/api/bench.py
press/press/doctype/bench/bench.py
press/press/doctype/bench_update/bench_update.json
press/press/doctype/bench_update/bench_update.py
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/team/team.py

Unneccesary misdirection and duplication of state. Doesn't appear to be used
anywhere other than one function which can probably refactored to use something
else. If it can't this PR will be closed.

fix: remove `Bench Update`.status

---

press/press/doctype/usage_record/usage_record.py

Sometimes duplicate usage record for same resource gets created in the same background job and validation is skipped 
This prevents the duplication by checking before submission of UR

fix: check for duplicate records before submit

---

press/press/doctype/account_request/account_request.py
press/saas/doctype/saas_settings/saas_settings.json
press/saas/doctype/saas_settings/saas_settings.py

If we configure an email account under `SaaS Settings`, that mail will be used to send verification mails instead of default sending mail.

feat: custom mail account for current saas signup

---

dashboard/src2/components/group/UpdateReleaseGroupDialog.vue
press/press/doctype/bench/bench.json
press/press/doctype/bench/bench.py
press/press/doctype/release_group/release_group.py

Two changes:
- Changes **Use regular updates** to **Use in place updates**
- Prevents in place updates if last in place update for a bench failed
docs updated: https://frappecloud.com/docs/in-place-updates

fix: UX for inplace updates

---

deployment/nginx.conf
press/api/developer/saas.py
press/www/saas/billing.js

We have added a simplified login for SaaS sites, so that user can login to frappe cloud easily.
PR - https://github.com/frappe/press/pull/2233
We need to allow cross-site-request for those SaaS apis.
APIs - https://github.com/frappe/press/blob/master/press/api/developer/saas.py#L84-L203

fix: cors issue for saas login apis

---

press/press/doctype/razorpay_webhook_log/razorpay_webhook_log.py

- FC Error Log Trace ID - 0717384a-1d9e-4707-bfa3-eb6dd2d83bae
- if order_id not found in webhook payload, ignore the call
- Sentry event - PRESS-7A2
- if `razorpay payment record` status is pending, then only proceed for capturing that payment
- silently ignore 'id provided does not exist' error while manually capturing the payment (because anyway razorpay will autocapture the payment)

fix(razorpay): razorpay order confirmation and manual payment capture webhook errors

---

press/press/doctype/site/saas_pool.py

- fix(HybridPool): check for specific app as per record instead of erpnext app
- fix(HybridPool): dont stop create pooling only one hybrid pool has been replenished

fix(HybridSaaSPool): create standby sites for all hybrid pool rules

---

press/api/site.py
press/api/tests/test_site.py
press/press/doctype/server/test_server.py
press/press/doctype/site/site.py

- fix(tests): in get_installed_apps fn, set query_filters to blank dict in case of None
- fix(tests): move to unnittest.TestCase from FrappeTestCase due to issues of test discoverability
- fix(tests): in plan validation hooks to check allowed apps use the class variable instead of querying in db as changes not commited yet
-  fix(tests): while testing test_new_fn_creates_site_and_subscription make sure to use a public server
- the subscription_plan gets overriden if server is not public and it assumes that as dedicated server
- https://github.com/frappe/press/blob/96734b1fcc2e35b51e29acfb796b09d11362f483/press/press/doctype/site/site.py#L462-L485

fix(tests): fix broken testcases

---

dashboard/src2/components/settings/TeamSettingsDialog.vue

Should not be used by people who aren't aware of it's dangers.

fix: remove inplace enable flag

---

press/press/doctype/site/site.py
press/saas/api/site.py
press/saas/doctype/product_trial/product_trial.py

 chore(saas): misc saas flow fixes and tweaks

---

dashboard/src2/components/SitePlansCards.vue
dashboard/src2/components/site/NewSiteAppSelector.vue
dashboard/src2/pages/NewReleaseGroup.vue
dashboard/src2/pages/NewSite.vue
press/api/bench.py
press/api/site.py
press/press/doctype/app_group/app_group.json
press/press/doctype/app_group/app_group.py
press/press/doctype/press_settings/press_settings.json
press/press/doctype/press_settings/press_settings.py

feat: provision to configure default apps while creating bench

---

dashboard/src2/pages/saas/LoginToSite.vue
press/saas/README.md
press/saas/doctype/product_trial/product_trial.json
press/saas/doctype/product_trial/product_trial.py

Related https://github.com/frappe/press/issues/2281

feat(saas): support to configure the redirection url for site after login/signup

---

dashboard/src2/components/SiteDatabaseAccessDialog.vue
dashboard/src2/components/site_database_user/SiteDatabaseAddEditUserDialog.vue
dashboard/src2/components/site_database_user/SiteDatabaseUserCredentialDialog.vue
press/agent.py
press/patches.txt
press/patches/v0_7_0/set_label_for_site_database_user.py
press/press/doctype/agent_job/agent_job.py
press/press/doctype/site/site.js
press/press/doctype/site/site.json
press/press/doctype/site/site.py
press/press/doctype/site_database_user/site_database_user.json
press/press/doctype/site_database_user/site_database_user.py

Fixes https://github.com/frappe/press/issues/2315 https://github.com/frappe/press/issues/2317
(Check issue for more details)
**Previews -**
**Manage Users -**
**Add Users -**
**Error regarding database connection limit during adding new user -**
**Edit Database User -**
> Currently, user can't change database connection limit once added
Agent PR - https://github.com/frappe/agent/pull/145

feat: support to configure max database connections for site database users

---

press/press/doctype/app_release/app_release.py

feat: use bench python to validate python syntax in builds

---

press/api/analytics.py
press/press/doctype/bench/bench.py
press/press/doctype/site/backups.py
press/press/doctype/site/site.py
press/press/doctype/site_update/site_update.py
press/press/doctype/virtual_disk_snapshot/virtual_disk_snapshot.py
press/press/report/binary_log_browser/binary_log_browser.py
press/utils/__init__.py

Follow up to https://github.com/frappe/frappe/pull/28093 so I can drop the pytz dependency

refactor: drop pytz

---

press/fixtures/mariadb_variable.json

For MariaDB >= 10.2.4, Default is set to MIXED

chore: configurable binlog format: MIXED, ROW, STATEMENT

---

press/docker/Dockerfile
press/docker/wkhtmltopdf.md
press/press/doctype/deploy_candidate/deploy_candidate.json
press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/server/server.json
press/press/doctype/server/server.py

Uses [docker multi-platform builds](https://docs.docker.com/build/building/multi-platform/).
Depends on frappe/agent@c4fb7bed224f323758b597e11c5ffbe48746f152

fix(build): Support for ARM builds

---

press/press/doctype/invoice/invoice.py

Item descriptions were only set for Site document type and set as Prepaid credits implicitly in the print format for all others which would make the invoice look something like this

fix: invoice item descriptions for missing document types

---

dashboard/src2/components/devtools/database/SQLCodeEditor.vue
dashboard/src2/pages/devtools/database/DatabaseSQLPlayground.vue

Fixes #2379
[Screencast from 12-21-2024 12:02:44 PM.webm](https://github.com/user-attachments/assets/e2692300-443e-4e46-af3b-461945f52bf3)

feat(sql-playground): allow to run selected queries of editor

---

dashboard/src2/components/site_database_user/SiteDatabaseUserCredentialDialog.vue
press/api/__init__.py
press/utils/__init__.py

Fixes https://github.com/frappe/press/issues/2364
- Some SSL Instructions + Documentation link added
- Users can download the ssl fullchain from dashboard iteself.
- Validated download ssl cert chain with looker studio. It's working.

feat(site-database-user): add ssl instructions for database user

---

.cspell.json
press/press/doctype/agent_job/agent_job.py
press/press/doctype/agent_job/agent_job_notifications.py
press/press/doctype/site/site.py

- **fix(agent-job-notifications): Handle can't connect to mysql errs**
- **chore(subscription): Correct spelling**
- **fix(agent-job-notification): Handle corrupt backup restore attempts**
- **fix(agent-job-notification): Handle incompatible backup errs**
fixes #2363

chore(agent-job-notifications): Handle more error types

---

press/press/doctype/release_group/release_group.py

- Merge default+short workers on v14 onwards https://github.com/frappe/press/pull/893
- Use RQ worker-pool on v15 onwards https://github.com/frappe/press/pull/1376
- Use threads v15 onwards https://github.com/frappe/press/pull/1218 https://github.com/frappe/press/pull/1255  https://github.com/frappe/press/pull/1278

perf(bench): Enable optimizations on recent versions

---

press/press/doctype/site/site.py
press/press/doctype/site_plan/site_plan.py

It's extra overhead. It doesn't do anything right now as it is kept
very high to avoid ever hitting that limit on dedicated servers.
closes https://github.com/frappe/caffeine/issues/48

perf: Do not apply usage limit tracking on dedicated servers

---

dashboard/src2/components/NavigationItems.vue
dashboard/src2/components/billing/BuyCreditsRazorpay.vue
dashboard/src2/components/billing/PaymentDetails.vue
dashboard/src2/components/partners/BuyPartnerCreditsRazorpay.vue
dashboard/src2/components/partners/BuyPartnerCreditsStripe.vue
dashboard/src2/components/partners/PartnerContribution.vue
dashboard/src2/components/partners/PartnerCreditsForm.vue
dashboard/src2/components/partners/PartnerMembers.vue
dashboard/src2/components/partners/PartnerOverview.vue
dashboard/src2/pages/BillingInvoices.vue
dashboard/src2/pages/Partners.vue
dashboard/src2/router.js
press/api/billing.py
press/api/client.py
press/api/partner.py
press/partner/doctype/partner_tier/partner_tier.js
press/partner/doctype/partner_tier/partner_tier.json
press/partner/doctype/partner_tier/partner_tier.py
press/partner/doctype/partner_tier/test_partner_tier.py
press/press/doctype/balance_transaction/balance_transaction.json
press/press/doctype/balance_transaction/balance_transaction.py
press/press/doctype/invoice/invoice.json
press/press/doctype/invoice/invoice.py
press/press/doctype/press_settings/press_settings.json
press/press/doctype/press_settings/press_settings.py
press/press/doctype/razorpay_payment_record/razorpay_payment_record.json
press/press/doctype/razorpay_payment_record/razorpay_payment_record.py
press/press/doctype/team/team.py

This will allow partners to pay for Partnership renewal Fee directly from FC To enable this a new Invoice type and Balance Transaction Type called as Partnership Fee has been introduced.
ToDo:
- Show Terms & Conditions check acting as Partner Agreement
- Send Email on Successful renewal & Update renewal date

feat(partner): Partnership Fees via dashboard

---

press/patches.txt
press/press/doctype/subscription/test_subscription.py
press/press/doctype/usage_record/patches/add_unique_constraint.py
press/press/doctype/usage_record/usage_record.py

Revert "fix(usage-record): Add Unique constraints"

---

press/api/analytics.py

These will essentially show more info about requests to
- /api/method/run_doc_method 
- /api/method/frappe.desk.query_report.run
And background reports

feat(site-analytics): Add functions for more detailed charts

---

press/press/doctype/invoice/invoice.py
press/press/doctype/stripe_payment_event/stripe_payment_event.py

When stripe invoice is in processing (payments pending) state, invoices cannot be marked as void and thus the fc invoice remains unpaid even when credits are available and applied.
> Note: This has been tested in a very hacky manner since there is no way to set invoice in processing state. You can either immediately fail or succeeded a transaction on Stripe.

fix(payments): Set invoice status as Paid when stripe invoice is pending

---

press/api/partner.py
press/press/doctype/invoice/invoice.py
press/press/doctype/team/team.py

* Remove redundant code block from Invoice
* Fetch certificate count of partner

fix(partner): Remove legacy contract check

---

press/press/doctype/mpesa_setup/mpesa_connector.py

Ensure `CustomerPayBillOnline` is used for both production and sandbox environments in Mpesa Express (STK Push) transactions.

fix(mpesa): Use CustomPaybillOnline for both prod and sandbox environment

---

dashboard/src2/components/billing/mpesa/BuyPrepaidCreditsMpesa.vue

Make tax id mendatory while initiating mpesa payments.

fix(mpesa): Make tax id mandatory for vat purpose

---

dashboard/src2/components/settings/profile/AccountProfile.vue
press/api/account.py
press/press/doctype/team/team.py

* Move all the validation to client side
* Finalize only once and redirect them to Invoices page next time
* If payment mode is prepaid credits, allow to refill wallet
* If amount_due <= $5 or equivalent, allow to disable account (skip validation)

refactor(billing): Disable account

---

press/docker/Dockerfile

Required for building certain packages that depend on env and available libs to compile.

build: add pkg-config in dockerfile

---

press/press/report/marketplace_app_repository_visibility/marketplace_app_repository_visibility.py
press/templates/emails/marketplace_app_visibility.html

Report also filters only published apps and active app sources

fix(marketplace-report): Group by repo url for fewer iterations

---

press/hooks.py
press/press/doctype/virtual_disk_snapshot/virtual_disk_snapshot.json
press/press/doctype/virtual_disk_snapshot/virtual_disk_snapshot.py
press/press/doctype/virtual_machine/virtual_machine.py

Fixes #2558
Fixes #2557
- Exclude temporary volumes from snapshotting
- Keep snapshot of server in last 2 hour for faser snapshotting in physical backup
- Calling it `Rolling Snapshot`
- We will only delete old rolling snapshot, once the new one become available, else we can't get benefit from old one.

feat: Rolling Snapshot for Physical Backup

---

press/hooks.py
press/infrastructure/doctype/ssh_access_audit/ssh_access_audit.py
press/overrides.py
press/press/doctype/ansible_console/ansible_console.py

extends https://github.com/frappe/press/pull/2559
alternate to https://github.com/frappe/press/commit/d90dfb50eba4bea18c54ea6f4372f22d1928b310
- Ansible creates tmp files while running plays
- The files are usually deleted but tmp directories in which the file got
created is often left out, so that slowly grows (not THAT fast afaik)
This new job clears all directories older than 1 hour, every hour. This
avoids problem with racey deletes or creating a new tmp file in 
directory that got erased by us in previous jobs.
Things to review:
- threshold logic
- "growth rate" - if it's too high then frequency might not be enough. 
I am only seeing few MBs of growth so eh. 
- is it safe to remove ?

fix: Periodically cleanup ansible tmp files

---

press/playbooks/reset_swap.yml
press/playbooks/roles/remove_swap/tasks/main.yml
press/playbooks/roles/swap/tasks/main.yml
press/press/doctype/server/server.js
press/press/doctype/server/server.py

We can now reset swap to desired number (including 0). Increase swap functionality is
kept, just in case for now.
Can be a reaction to swap full when it is 8 GB or above to avoid
suffering

feat(server): Allow removing swap

---

press/docker/Dockerfile
press/press/doctype/deploy_candidate/deploy_candidate.py

feat(build): Removed distutils for python >= 3.12

---

dashboard/src/views/bench/BenchSites.vue
dashboard/src/views/site/Site.vue
dashboard/src/views/site/Sites.vue
dashboard/src2/objects/site.js
press/press/doctype/site/site.js

Redirect to `https://<sitename>/apps` instead of `https://<sitename` if `Visit Site` button is clicked

fix: redirect to /apps if Visit Site is clicked

---

press/fixtures/mariadb_variable.json

https://mariadb.com/kb/en/innodb-system-variables/#innodb_stats_persistent_sample_pages
20 is way too low, we can easily 10x this and it will barely have any
real cost for us. So 10x-ing this for now.
ref: https://www.percona.com/blog/correcting-mysql-inaccurate-table-statistics-for-better-execution-plan/
We also need to upgrade to 11.x someday soon... when 11.8 is stable.

perf: Add innodb_stats_persistent_sample_pages to mariadb variables

---

press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate_build/deploy_candidate_build.py

Generating ssh keys from deploy candidate; fixed missing build dir error.

fix(ssh-keys): Pass build dir to generate_ssh_keys

---

press/press/doctype/deploy_candidate/deploy_notifications.py
press/press/doctype/deploy_candidate_build/deploy_candidate_build.py

Build failure notifications failing and deploy candidate build being passed instead of deploy candidate

fix(notifications): Build failure notification with correct candidate

---

press/overrides.py

The rate of tmp file growth is slow but it's approaching 1GB over ~ month.
So, better to keep cleaning this up periodically still.

fix: Delete ansible files when running in NOFORK mode

---

press/press/doctype/deploy_candidate_build/deploy_candidate_build.py

This save was added to ensure user private/public keys and certificate was saved, however `generate_user_keys` explicitly calls save on deploy candidate

fix(timestamp-error): Remove explicit candidate save

---

press/press/doctype/deploy_candidate/deploy_candidate.py
press/press/doctype/deploy_candidate_build/deploy_candidate_build.py

- Fail the current build doctype instead of setting it's status to scheduled (leads to race condition scheduling)
- In the new deploy candidate build increase the retry count by one, so that after 3 retries we stop.

fix(retry): Retry count is increased in a new deploy candidate build

---

press/press/doctype/deploy_candidate_variable/deploy_candidate_variable.json
press/press/doctype/deploy_candidate_variable/deploy_candidate_variable.py

This is to accommodate large text values/API keys in `Deploy Candidate`

fix(env-var): Changed deploy candidate env var field from data to text

---

press/press/doctype/inspect_trace_id/inspect_trace_id.js
press/press/doctype/inspect_trace_id/inspect_trace_id.json
press/press/doctype/inspect_trace_id/inspect_trace_id.py
press/press/doctype/inspect_trace_id/test_inspect_trace_id.py

A very basic "search request/job log for this trace ID"
Towards https://github.com/frappe/press/issues/2494

feat: Inspect a request/job by trace ID

---

press/hooks.py
press/press/doctype/tls_certificate/tls_certificate.js
press/press/doctype/tls_certificate/tls_certificate.json
press/press/doctype/tls_certificate/tls_certificate.py

feat: Provision to add Custom TLS

---

press/agent.py
press/fixtures/agent_job_type.json
press/hooks.py
press/press/doctype/agent_job/agent_job.py
press/press/doctype/database_server/database_server.json
press/press/doctype/database_server/database_server.py
press/press/doctype/mariadb_binlog/mariadb_binlog.js
press/press/doctype/mariadb_binlog/mariadb_binlog.json
press/press/doctype/mariadb_binlog/mariadb_binlog.py
press/press/doctype/remote_file/remote_file.py

Related https://github.com/frappe/press/issues/2566

feat(binlog): Manage & Upload binlogs to s3

---

dashboard/src2/components/ChurnFeedbackDialog.vue
dashboard/src2/components/billing/AddExchangeRate.vue
dashboard/src2/objects/bench.ts

Replacing deep imports from frappe-ui with imports from the entry file.
`import component from "frappe-ui/src/components/component.vue"` → `import { component } from "frappe-ui"`
This will break whenever frappe-ui is upgraded with this change: https://github.com/frappe/frappe-ui/pull/308
In general, its better to avoid deep imports to avoid breakage from changes in library's folder structure.

fix: replace deep imports from frappe-ui

---

press/api/server.py
press/press/doctype/cluster/cluster.json
press/press/doctype/cluster/cluster.py

ARM server creation is limited by the region, til ARM AMI's are available in all supported region.

feat: Provision ARM servers only

---

press/docker/Dockerfile

This should allow tweaking bench, framework etc when we detect that it's a docker build. 
Examples: 
- https://github.com/frappe/frappe/pull/33051 
- https://github.com/frappe/bench/pull/1642

feat: variable to identify docker build

---

press/press/doctype/build_metric/build_metric.py
press/press/doctype/build_metric/build_metric_types.py

- Change build metrics to only count `deploy_after_build` flags.
- Show the arm / intel build split.

feat(metric): Update metrics counts to disregard migration builds

---

press/agent.py
press/api/site.py
press/press/doctype/site/site.py
press/press/doctype/site_migration/site_migration.py

When migrating servers from Scaleway, large sites may not have enough
space for backup. Avoid that in advance.

fix(site-migration): Add space validation for taking backup

---

press/press/doctype/cluster_plan/cluster_plan.py
press/press/doctype/server_plan/server_plan.py
press/press/doctype/site_plan/site_plan.py

Add validations for disabling active plans which are used in any of active subscriptions.

fix(server-plan): Validate active subs before disabling

---

press/press/doctype/bench/bench.py

Even if the DB has `datetime(6)` type set for `last_archive_failure`, it gets fatched as `datetime_str` causing the below error. This PR fixes the typeError.
```py
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
```

fix: Get datetime format of `last_archive_failure` field in `check_last_archive` method

---

press/exceptions.py
press/press/doctype/deploy_candidate_build/deploy_candidate_build.py
press/press/doctype/release_group/release_group.py

When adding new server to bench group, we fetch the image form the last successful deploy candidate build, however it's possible that the image has been pruned from the registry in that case we need to trigger a new deploy.

feat(deploy): Image in registry check

---

press/hooks.py
press/press/doctype/registry_server/registry_server.py

Deletion of older images is now managed in code instead of being a server script.

chore(registry): Moving out of server scripts

---

dashboard/src/pages/signup/LoginToSite.vue
press/saas/doctype/product_trial_request/product_trial_request.py

Resolve an infinite loading state during login when the WebSocket connection fails.
The initial socket failure correctly triggered the fallback mechanism, but the fallback code itself contained a bug that prevented the login process from completing. This patch corrects the logic in the fallback handler to ensure login proceeds using the alternative HTTP polling method.
The websocket is not pushing updated status as its broken. The get_progress function, which can ensure login using the polling method doesn't have "status" in the JSON response. As status is not sent in response, the page shows "Logging in" message for very longtime without any sign of moving to product setup

fix(signup):  Fix login timeout fallback logic

---

press/press/doctype/analytics_server/analytics_server.json
press/press/doctype/analytics_server/analytics_server.py
press/press/doctype/database_server/database_server.json
press/press/doctype/database_server/database_server.py
press/press/doctype/log_server/log_server.json
press/press/doctype/log_server/log_server.py
press/press/doctype/monitor_server/monitor_server.json
press/press/doctype/monitor_server/monitor_server.py
press/press/doctype/proxy_server/proxy_server.json
press/press/doctype/proxy_server/proxy_server.py
press/press/doctype/registry_server/registry_server.json
press/press/doctype/registry_server/registry_server.py
press/press/doctype/server/server.json
press/press/doctype/server/server.py
press/press/doctype/tls_certificate/tls_certificate.py
press/press/doctype/trace_server/trace_server.json
press/press/doctype/trace_server/trace_server.py

Fixes https://github.com/frappe/press/issues/3164
Instead of relying on `Ansible Play` status, manage TLS Renewal failure in a flag in server doctypes.
After TLS Certificate Renewal,
- If `Server` is `Active`, trigger immediate tls certificate update
- Else, just mark the flag `tls_certificate_renewal_failed` on server doctype. BG Job will retry the renewal later.

fix: Wildcard TLS Renewal Retry Irrespective of Server Status

---

press/press/doctype/bench/bench.py

- Multiple benches created in parallel run into same port offsets.
- Need to take a lock for txnA to finish before txnB can take a lock to get unused port.
- Quick commit once the port is assigned to release lock.

fix(bench): Port offset conflicts

---

press/fixtures/press_job_type.json
press/press/doctype/press_job_step/press_job_step.py
press/press/doctype/server/server.js
press/press/doctype/server/server.json
press/press/doctype/server/server.py
press/press/doctype/virtual_machine/virtual_machine.json
press/press/doctype/virtual_machine/virtual_machine.py

- Add action to allocate an Elastic IP to an EC2 instance and trigger sync from the associated Virtual Machine
- Add a step in sync under update_servers to update the new `is_static_ip` read-only field in Server if the returned IP is Elastic

feat(cluster): Add elastic ip integration to ec2 servers (#3288)

---

press/playbooks/roles/mount/tasks/main.yml

Ansible try to mark the step as fail
Because, after fixing filesystem e2fsck return 1

fix(mount): E2fsck's status code 0 and 1 both is valid

---

press/hooks.py
press/patches.txt
press/press/doctype/site/site.py
press/saas/doctype/product_trial/product_trial.py
press/saas/doctype/product_trial_request/patches/set_subscription_created_flag.py
press/saas/doctype/product_trial_request/product_trial_request.json
press/saas/doctype/product_trial_request/product_trial_request.py

This PR moves the creating subscription process for precreated site from the sign up flow into background job that runs for every 5 mins and take care of it there.

fix(signups): Move create subscription part as bg job

---

press/press/doctype/account_request/account_request.py
press/press/doctype/site/site.py

This PR fixes the issue that allows the user who signed up for Frappe account, but didn't continue finishing the setup account process and later came back and logged in. The login started to throw permission issue as the account request key got expired and they were struck in that part forever. This fix regenerates the account key if expired and ensures that user can continue setup of the account process

fix(login): Request key expired signed up user could not login

---

press/press/doctype/bench/bench.js

Routing was refactored a while ago, but this link wasn't fixed.

fix(desk): visit dashboard link for bench doc

---

press/hooks.py
press/press/doctype/app/app.py
press/press/doctype/bench/bench.py
press/saas/doctype/product_trial/product_trial.py

There are certain hourly jobs, which do some syncing / polling in a loop. That causes two issues -
- Sometimes the job consume too much memory, as it's fetching data of all benches [?].
- Most importantly, it block worker restart while deploying some changes. And we had to force stop those.
Also, move small batch jobs to `sync` queue. We don't restart this custom queue frequently. So that will not block deployment

perf: Move long running jobs to small jobs with batch

---

dashboard/src/components/AlertBanner.vue
dashboard/src/components/SiteOverview.vue
dashboard/src/components/site/SiteEnableMonitoringDialog.vue
dashboard/src/objects/site.js
press/api/monitoring.py
press/api/site.py
press/press/doctype/database_server/database_server.json
press/press/doctype/database_server/database_server.py
press/press/doctype/server/server.json
press/press/doctype/server/server.py
press/press/doctype/site/site.js
press/press/doctype/site/site.json
press/press/doctype/site/site.py
press/press/doctype/site_activity/site_activity.json
press/press/doctype/site_activity/site_activity.py
press/templates/emails/disabled_site_monitoring.html

Fixes https://github.com/frappe/press/issues/3397
User can self-fix the issue and enable monitoring back - 
**Log activities in `Site Activity`  -** 
**User will receive a mail regarding the same -**

feat(monitoring): Add feature flag to disable monitoring

---

.github/workflows/validate-pr-title.yaml
dashboard/src/components/server/ServerCharts.vue
dashboard/src/objects/server.js
press/api/analytics.py
press/api/server.py
press/playbooks/install_cadvisor.yml
press/press/doctype/bench/bench.py
press/press/doctype/bench/test_bench.py
press/press/doctype/cluster/cluster.py
press/press/doctype/server/server.py
press/press/doctype/site/site.py
press/press/doctype/site_database_user/site_database_user.py
press/utils/__init__.py

- **fix(bench): Keep benches included in fatal site updates for some time**
- **fix(server): Setup cadvisor for all servers**
- Need it for setting housekeeping_interval to 10s by default
- Also rename the playbook and fn as the playbook works for x86 already
- **feat(server): Add charts for background jobs by site**
High cpu can also be caused by them
- **fix(cluster): Get public x86 images for new cluster**
- **test(bench): Test for fatal site update blocking archival**
- Also remove unnecessary util
- Also raise error on archival instead of print

fix(bench): Prevent dropping benches with recent fatal site update
